// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/admin.proto

package synclogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncLogAdminService_CreateStream_FullMethodName       = "/synclog.v1.SyncLogAdminService/CreateStream"
	SyncLogAdminService_DeleteStream_FullMethodName       = "/synclog.v1.SyncLogAdminService/DeleteStream"
	SyncLogAdminService_ListStreams_FullMethodName        = "/synclog.v1.SyncLogAdminService/ListStreams"
	SyncLogAdminService_TruncateStream_FullMethodName     = "/synclog.v1.SyncLogAdminService/TruncateStream"
	SyncLogAdminService_CompactStream_FullMethodName      = "/synclog.v1.SyncLogAdminService/CompactStream"
	SyncLogAdminService_SetStreamRetention_FullMethodName = "/synclog.v1.SyncLogAdminService/SetStreamRetention"
	SyncLogAdminService_ResetCursor_FullMethodName        = "/synclog.v1.SyncLogAdminService/ResetCursor"
	SyncLogAdminService_ListCursors_FullMethodName        = "/synclog.v1.SyncLogAdminService/ListCursors"
	SyncLogAdminService_GetStreamStats_FullMethodName     = "/synclog.v1.SyncLogAdminService/GetStreamStats"
)

// SyncLogAdminServiceClient is the client API for SyncLogAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncLogAdminService is the ops plane of the generic event log. Like the rest of
// synclog it is domain-agnostic: it speaks only streams, cursors, events, and seq.
type SyncLogAdminServiceClient interface {
	// Stream lifecycle
	CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*CreateStreamResponse, error)
	DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error)
	ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	// Compaction / retention
	TruncateStream(ctx context.Context, in *TruncateStreamRequest, opts ...grpc.CallOption) (*TruncateStreamResponse, error)
	CompactStream(ctx context.Context, in *CompactStreamRequest, opts ...grpc.CallOption) (*CompactStreamResponse, error)
	SetStreamRetention(ctx context.Context, in *SetStreamRetentionRequest, opts ...grpc.CallOption) (*SetStreamRetentionResponse, error)
	// Cursor admin. Normal consumers advance via SyncLogService.Ack; these RPCs
	// are for ops, migrations, and snapshot-based recovery.
	ResetCursor(ctx context.Context, in *ResetCursorRequest, opts ...grpc.CallOption) (*ResetCursorResponse, error)
	ListCursors(ctx context.Context, in *ListCursorsRequest, opts ...grpc.CallOption) (*ListCursorsResponse, error)
	// Stats
	GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error)
}

type syncLogAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncLogAdminServiceClient(cc grpc.ClientConnInterface) SyncLogAdminServiceClient {
	return &syncLogAdminServiceClient{cc}
}

func (c *syncLogAdminServiceClient) CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*CreateStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStreamResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_CreateStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStreamResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_DeleteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_ListStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) TruncateStream(ctx context.Context, in *TruncateStreamRequest, opts ...grpc.CallOption) (*TruncateStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TruncateStreamResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_TruncateStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) CompactStream(ctx context.Context, in *CompactStreamRequest, opts ...grpc.CallOption) (*CompactStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactStreamResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_CompactStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) SetStreamRetention(ctx context.Context, in *SetStreamRetentionRequest, opts ...grpc.CallOption) (*SetStreamRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStreamRetentionResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_SetStreamRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) ResetCursor(ctx context.Context, in *ResetCursorRequest, opts ...grpc.CallOption) (*ResetCursorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetCursorResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_ResetCursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) ListCursors(ctx context.Context, in *ListCursorsRequest, opts ...grpc.CallOption) (*ListCursorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCursorsResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_ListCursors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogAdminServiceClient) GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamStatsResponse)
	err := c.cc.Invoke(ctx, SyncLogAdminService_GetStreamStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncLogAdminServiceServer is the server API for SyncLogAdminService service.
// All implementations must embed UnimplementedSyncLogAdminServiceServer
// for forward compatibility.
//
// SyncLogAdminService is the ops plane of the generic event log. Like the rest of
// synclog it is domain-agnostic: it speaks only streams, cursors, events, and seq.
type SyncLogAdminServiceServer interface {
	// Stream lifecycle
	CreateStream(context.Context, *CreateStreamRequest) (*CreateStreamResponse, error)
	DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamResponse, error)
	ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error)
	// Compaction / retention
	TruncateStream(context.Context, *TruncateStreamRequest) (*TruncateStreamResponse, error)
	CompactStream(context.Context, *CompactStreamRequest) (*CompactStreamResponse, error)
	SetStreamRetention(context.Context, *SetStreamRetentionRequest) (*SetStreamRetentionResponse, error)
	// Cursor admin. Normal consumers advance via SyncLogService.Ack; these RPCs
	// are for ops, migrations, and snapshot-based recovery.
	ResetCursor(context.Context, *ResetCursorRequest) (*ResetCursorResponse, error)
	ListCursors(context.Context, *ListCursorsRequest) (*ListCursorsResponse, error)
	// Stats
	GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error)
	mustEmbedUnimplementedSyncLogAdminServiceServer()
}

// UnimplementedSyncLogAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncLogAdminServiceServer struct{}

func (UnimplementedSyncLogAdminServiceServer) CreateStream(context.Context, *CreateStreamRequest) (*CreateStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStream not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStream not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) TruncateStream(context.Context, *TruncateStreamRequest) (*TruncateStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TruncateStream not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) CompactStream(context.Context, *CompactStreamRequest) (*CompactStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompactStream not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) SetStreamRetention(context.Context, *SetStreamRetentionRequest) (*SetStreamRetentionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStreamRetention not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) ResetCursor(context.Context, *ResetCursorRequest) (*ResetCursorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetCursor not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) ListCursors(context.Context, *ListCursorsRequest) (*ListCursorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCursors not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamStats not implemented")
}
func (UnimplementedSyncLogAdminServiceServer) mustEmbedUnimplementedSyncLogAdminServiceServer() {}
func (UnimplementedSyncLogAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeSyncLogAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncLogAdminServiceServer will
// result in compilation errors.
type UnsafeSyncLogAdminServiceServer interface {
	mustEmbedUnimplementedSyncLogAdminServiceServer()
}

func RegisterSyncLogAdminServiceServer(s grpc.ServiceRegistrar, srv SyncLogAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncLogAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncLogAdminService_ServiceDesc, srv)
}

func _SyncLogAdminService_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_CreateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).CreateStream(ctx, req.(*CreateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_DeleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).DeleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_DeleteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).DeleteStream(ctx, req.(*DeleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_ListStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).ListStreams(ctx, req.(*ListStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_TruncateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).TruncateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_TruncateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).TruncateStream(ctx, req.(*TruncateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_CompactStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).CompactStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_CompactStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).CompactStream(ctx, req.(*CompactStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_SetStreamRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStreamRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).SetStreamRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_SetStreamRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).SetStreamRetention(ctx, req.(*SetStreamRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_ResetCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).ResetCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_ResetCursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).ResetCursor(ctx, req.(*ResetCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_ListCursors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCursorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).ListCursors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_ListCursors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).ListCursors(ctx, req.(*ListCursorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogAdminService_GetStreamStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogAdminServiceServer).GetStreamStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogAdminService_GetStreamStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogAdminServiceServer).GetStreamStats(ctx, req.(*GetStreamStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncLogAdminService_ServiceDesc is the grpc.ServiceDesc for SyncLogAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncLogAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synclog.v1.SyncLogAdminService",
	HandlerType: (*SyncLogAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStream",
			Handler:    _SyncLogAdminService_CreateStream_Handler,
		},
		{
			MethodName: "DeleteStream",
			Handler:    _SyncLogAdminService_DeleteStream_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _SyncLogAdminService_ListStreams_Handler,
		},
		{
			MethodName: "TruncateStream",
			Handler:    _SyncLogAdminService_TruncateStream_Handler,
		},
		{
			MethodName: "CompactStream",
			Handler:    _SyncLogAdminService_CompactStream_Handler,
		},
		{
			MethodName: "SetStreamRetention",
			Handler:    _SyncLogAdminService_SetStreamRetention_Handler,
		},
		{
			MethodName: "ResetCursor",
			Handler:    _SyncLogAdminService_ResetCursor_Handler,
		},
		{
			MethodName: "ListCursors",
			Handler:    _SyncLogAdminService_ListCursors_Handler,
		},
		{
			MethodName: "GetStreamStats",
			Handler:    _SyncLogAdminService_GetStreamStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synclog/v1/admin.proto",
}
