// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/admin.proto

package synclogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_NONE    JobState = 0
	JobState_JOB_STATE_PENDING JobState = 1
	JobState_JOB_STATE_RUNNING JobState = 2
	JobState_JOB_STATE_DONE    JobState = 3
	JobState_JOB_STATE_FAILED  JobState = 4
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_NONE",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_DONE",
		4: "JOB_STATE_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_NONE":    0,
		"JOB_STATE_PENDING": 1,
		"JOB_STATE_RUNNING": 2,
		"JOB_STATE_DONE":    3,
		"JOB_STATE_FAILED":  4,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_synclog_v1_admin_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_synclog_v1_admin_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{0}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=synclog.v1.JobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_synclog_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_NONE
}

type StreamRetention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	TtlDays       int32                  `protobuf:"varint,2,opt,name=ttl_days,json=ttlDays,proto3" json:"ttl_days,omitempty"`       // 0 = keep forever
	MaxEvents     int64                  `protobuf:"varint,3,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"` // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRetention) Reset() {
	*x = StreamRetention{}
	mi := &file_synclog_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRetention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRetention) ProtoMessage() {}

func (x *StreamRetention) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRetention.ProtoReflect.Descriptor instead.
func (*StreamRetention) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StreamRetention) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamRetention) GetTtlDays() int32 {
	if x != nil {
		return x.TtlDays
	}
	return 0
}

func (x *StreamRetention) GetMaxEvents() int64 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

type StreamStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	EventCount      int64                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	HeadSeq         uint64                 `protobuf:"varint,3,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SubscriberCount int64                  `protobuf:"varint,5,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamStats) Reset() {
	*x = StreamStats{}
	mi := &file_synclog_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStats) ProtoMessage() {}

func (x *StreamStats) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStats.ProtoReflect.Descriptor instead.
func (*StreamStats) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStats) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamStats) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StreamStats) GetHeadSeq() uint64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *StreamStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *StreamStats) GetSubscriberCount() int64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

type CreateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamRequest) Reset() {
	*x = CreateStreamRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamRequest) ProtoMessage() {}

func (x *CreateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type CreateStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *Stream                `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamResponse) Reset() {
	*x = CreateStreamResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamResponse) ProtoMessage() {}

func (x *CreateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateStreamResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStreamResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type DeleteStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamRequest) Reset() {
	*x = DeleteStreamRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamRequest) ProtoMessage() {}

func (x *DeleteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamRequest.ProtoReflect.Descriptor instead.
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type DeleteStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamResponse) Reset() {
	*x = DeleteStreamResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamResponse) ProtoMessage() {}

func (x *DeleteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamResponse.ProtoReflect.Descriptor instead.
func (*DeleteStreamResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStreamResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListStreamsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListStreamsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListStreamsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*Stream              `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListStreamsResponse) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *ListStreamsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TruncateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	BeforeSeq     uint64                 `protobuf:"varint,2,opt,name=before_seq,json=beforeSeq,proto3" json:"before_seq,omitempty"` // remove events with seq < before_seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateStreamRequest) Reset() {
	*x = TruncateStreamRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateStreamRequest) ProtoMessage() {}

func (x *TruncateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateStreamRequest.ProtoReflect.Descriptor instead.
func (*TruncateStreamRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *TruncateStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *TruncateStreamRequest) GetBeforeSeq() uint64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

type TruncateStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int64                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateStreamResponse) Reset() {
	*x = TruncateStreamResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateStreamResponse) ProtoMessage() {}

func (x *TruncateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateStreamResponse.ProtoReflect.Descriptor instead.
func (*TruncateStreamResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *TruncateStreamResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

// CompactStream removes events below the minimum cursor across all subscribers.
type CompactStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactStreamRequest) Reset() {
	*x = CompactStreamRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactStreamRequest) ProtoMessage() {}

func (x *CompactStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactStreamRequest.ProtoReflect.Descriptor instead.
func (*CompactStreamRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *CompactStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type CompactStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactStreamResponse) Reset() {
	*x = CompactStreamResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactStreamResponse) ProtoMessage() {}

func (x *CompactStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactStreamResponse.ProtoReflect.Descriptor instead.
func (*CompactStreamResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *CompactStreamResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type SetStreamRetentionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retention     *StreamRetention       `protobuf:"bytes,1,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStreamRetentionRequest) Reset() {
	*x = SetStreamRetentionRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStreamRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStreamRetentionRequest) ProtoMessage() {}

func (x *SetStreamRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStreamRetentionRequest.ProtoReflect.Descriptor instead.
func (*SetStreamRetentionRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *SetStreamRetentionRequest) GetRetention() *StreamRetention {
	if x != nil {
		return x.Retention
	}
	return nil
}

type SetStreamRetentionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retention     *StreamRetention       `protobuf:"bytes,1,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStreamRetentionResponse) Reset() {
	*x = SetStreamRetentionResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStreamRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStreamRetentionResponse) ProtoMessage() {}

func (x *SetStreamRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStreamRetentionResponse.ProtoReflect.Descriptor instead.
func (*SetStreamRetentionResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *SetStreamRetentionResponse) GetRetention() *StreamRetention {
	if x != nil {
		return x.Retention
	}
	return nil
}

type ResetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCursorRequest) Reset() {
	*x = ResetCursorRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCursorRequest) ProtoMessage() {}

func (x *ResetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCursorRequest.ProtoReflect.Descriptor instead.
func (*ResetCursorRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ResetCursorRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *ResetCursorRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ResetCursorRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ResetCursorRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ResetCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *SubscriberCursor      `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCursorResponse) Reset() {
	*x = ResetCursorResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCursorResponse) ProtoMessage() {}

func (x *ResetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCursorResponse.ProtoReflect.Descriptor instead.
func (*ResetCursorResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ResetCursorResponse) GetCursor() *SubscriberCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListCursorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCursorsRequest) Reset() {
	*x = ListCursorsRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCursorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorsRequest) ProtoMessage() {}

func (x *ListCursorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorsRequest.ProtoReflect.Descriptor instead.
func (*ListCursorsRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListCursorsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type ListCursorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursors       []*SubscriberCursor    `protobuf:"bytes,1,rep,name=cursors,proto3" json:"cursors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCursorsResponse) Reset() {
	*x = ListCursorsResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCursorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorsResponse) ProtoMessage() {}

func (x *ListCursorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorsResponse.ProtoReflect.Descriptor instead.
func (*ListCursorsResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ListCursorsResponse) GetCursors() []*SubscriberCursor {
	if x != nil {
		return x.Cursors
	}
	return nil
}

type GetStreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsRequest) Reset() {
	*x = GetStreamStatsRequest{}
	mi := &file_synclog_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsRequest) ProtoMessage() {}

func (x *GetStreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetStreamStatsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *StreamStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsResponse) Reset() {
	*x = GetStreamStatsResponse{}
	mi := &file_synclog_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsResponse) ProtoMessage() {}

func (x *GetStreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *GetStreamStatsResponse) GetStats() *StreamStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_synclog_v1_admin_proto protoreflect.FileDescriptor

const file_synclog_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x16synclog/v1/admin.proto\x12\n" +
	"synclog.v1\x1a\x16synclog/v1/event.proto\"H\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.synclog.v1.JobStateR\x05state\"h\n" +
	"\x0fStreamRetention\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x19\n" +
	"\bttl_days\x18\x02 \x01(\x05R\attlDays\x12\x1d\n" +
	"\n" +
	"max_events\x18\x03 \x01(\x03R\tmaxEvents\"\xb0\x01\n" +
	"\vStreamStats\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x03R\n" +
	"eventCount\x12\x19\n" +
	"\bhead_seq\x18\x03 \x01(\x04R\aheadSeq\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10subscriber_count\x18\x05 \x01(\x03R\x0fsubscriberCount\"2\n" +
	"\x13CreateStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"B\n" +
	"\x14CreateStreamResponse\x12*\n" +
	"\x06stream\x18\x01 \x01(\v2\x12.synclog.v1.StreamR\x06stream\"2\n" +
	"\x13DeleteStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"0\n" +
	"\x14DeleteStreamResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"a\n" +
	"\x12ListStreamsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"k\n" +
	"\x13ListStreamsResponse\x12,\n" +
	"\astreams\x18\x01 \x03(\v2\x12.synclog.v1.StreamR\astreams\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x15TruncateStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"before_seq\x18\x02 \x01(\x04R\tbeforeSeq\"2\n" +
	"\x16TruncateStreamResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x03R\aremoved\"3\n" +
	"\x14CompactStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\":\n" +
	"\x15CompactStreamResponse\x12!\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.synclog.v1.JobR\x03job\"V\n" +
	"\x19SetStreamRetentionRequest\x129\n" +
	"\tretention\x18\x01 \x01(\v2\x1b.synclog.v1.StreamRetentionR\tretention\"W\n" +
	"\x1aSetStreamRetentionResponse\x129\n" +
	"\tretention\x18\x01 \x01(\v2\x1b.synclog.v1.StreamRetentionR\tretention\"\x84\x01\n" +
	"\x12ResetCursorRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"K\n" +
	"\x13ResetCursorResponse\x124\n" +
	"\x06cursor\x18\x01 \x01(\v2\x1c.synclog.v1.SubscriberCursorR\x06cursor\"1\n" +
	"\x12ListCursorsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"M\n" +
	"\x13ListCursorsResponse\x126\n" +
	"\acursors\x18\x01 \x03(\v2\x1c.synclog.v1.SubscriberCursorR\acursors\"4\n" +
	"\x15GetStreamStatsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"G\n" +
	"\x16GetStreamStatsResponse\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.synclog.v1.StreamStatsR\x05stats*v\n" +
	"\bJobState\x12\x12\n" +
	"\x0eJOB_STATE_NONE\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x12\n" +
	"\x0eJOB_STATE_DONE\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x042\x98\x06\n" +
	"\x13SyncLogAdminService\x12Q\n" +
	"\fCreateStream\x12\x1f.synclog.v1.CreateStreamRequest\x1a .synclog.v1.CreateStreamResponse\x12Q\n" +
	"\fDeleteStream\x12\x1f.synclog.v1.DeleteStreamRequest\x1a .synclog.v1.DeleteStreamResponse\x12N\n" +
	"\vListStreams\x12\x1e.synclog.v1.ListStreamsRequest\x1a\x1f.synclog.v1.ListStreamsResponse\x12W\n" +
	"\x0eTruncateStream\x12!.synclog.v1.TruncateStreamRequest\x1a\".synclog.v1.TruncateStreamResponse\x12T\n" +
	"\rCompactStream\x12 .synclog.v1.CompactStreamRequest\x1a!.synclog.v1.CompactStreamResponse\x12c\n" +
	"\x12SetStreamRetention\x12%.synclog.v1.SetStreamRetentionRequest\x1a&.synclog.v1.SetStreamRetentionResponse\x12N\n" +
	"\vResetCursor\x12\x1e.synclog.v1.ResetCursorRequest\x1a\x1f.synclog.v1.ResetCursorResponse\x12N\n" +
	"\vListCursors\x12\x1e.synclog.v1.ListCursorsRequest\x1a\x1f.synclog.v1.ListCursorsResponse\x12W\n" +
	"\x0eGetStreamStats\x12!.synclog.v1.GetStreamStatsRequest\x1a\".synclog.v1.GetStreamStatsResponseB<Z:github.com/gopherex/synclog/pkg/proto/synclog/v1;synclogv1b\x06proto3"

var (
	file_synclog_v1_admin_proto_rawDescOnce sync.Once
	file_synclog_v1_admin_proto_rawDescData []byte
)

func file_synclog_v1_admin_proto_rawDescGZIP() []byte {
	file_synclog_v1_admin_proto_rawDescOnce.Do(func() {
		file_synclog_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synclog_v1_admin_proto_rawDesc), len(file_synclog_v1_admin_proto_rawDesc)))
	})
	return file_synclog_v1_admin_proto_rawDescData
}

var file_synclog_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synclog_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_synclog_v1_admin_proto_goTypes = []any{
	(JobState)(0),                      // 0: synclog.v1.JobState
	(*Job)(nil),                        // 1: synclog.v1.Job
	(*StreamRetention)(nil),            // 2: synclog.v1.StreamRetention
	(*StreamStats)(nil),                // 3: synclog.v1.StreamStats
	(*CreateStreamRequest)(nil),        // 4: synclog.v1.CreateStreamRequest
	(*CreateStreamResponse)(nil),       // 5: synclog.v1.CreateStreamResponse
	(*DeleteStreamRequest)(nil),        // 6: synclog.v1.DeleteStreamRequest
	(*DeleteStreamResponse)(nil),       // 7: synclog.v1.DeleteStreamResponse
	(*ListStreamsRequest)(nil),         // 8: synclog.v1.ListStreamsRequest
	(*ListStreamsResponse)(nil),        // 9: synclog.v1.ListStreamsResponse
	(*TruncateStreamRequest)(nil),      // 10: synclog.v1.TruncateStreamRequest
	(*TruncateStreamResponse)(nil),     // 11: synclog.v1.TruncateStreamResponse
	(*CompactStreamRequest)(nil),       // 12: synclog.v1.CompactStreamRequest
	(*CompactStreamResponse)(nil),      // 13: synclog.v1.CompactStreamResponse
	(*SetStreamRetentionRequest)(nil),  // 14: synclog.v1.SetStreamRetentionRequest
	(*SetStreamRetentionResponse)(nil), // 15: synclog.v1.SetStreamRetentionResponse
	(*ResetCursorRequest)(nil),         // 16: synclog.v1.ResetCursorRequest
	(*ResetCursorResponse)(nil),        // 17: synclog.v1.ResetCursorResponse
	(*ListCursorsRequest)(nil),         // 18: synclog.v1.ListCursorsRequest
	(*ListCursorsResponse)(nil),        // 19: synclog.v1.ListCursorsResponse
	(*GetStreamStatsRequest)(nil),      // 20: synclog.v1.GetStreamStatsRequest
	(*GetStreamStatsResponse)(nil),     // 21: synclog.v1.GetStreamStatsResponse
	(*Stream)(nil),                     // 22: synclog.v1.Stream
	(*SubscriberCursor)(nil),           // 23: synclog.v1.SubscriberCursor
}
var file_synclog_v1_admin_proto_depIdxs = []int32{
	0,  // 0: synclog.v1.Job.state:type_name -> synclog.v1.JobState
	22, // 1: synclog.v1.CreateStreamResponse.stream:type_name -> synclog.v1.Stream
	22, // 2: synclog.v1.ListStreamsResponse.streams:type_name -> synclog.v1.Stream
	1,  // 3: synclog.v1.CompactStreamResponse.job:type_name -> synclog.v1.Job
	2,  // 4: synclog.v1.SetStreamRetentionRequest.retention:type_name -> synclog.v1.StreamRetention
	2,  // 5: synclog.v1.SetStreamRetentionResponse.retention:type_name -> synclog.v1.StreamRetention
	23, // 6: synclog.v1.ResetCursorResponse.cursor:type_name -> synclog.v1.SubscriberCursor
	23, // 7: synclog.v1.ListCursorsResponse.cursors:type_name -> synclog.v1.SubscriberCursor
	3,  // 8: synclog.v1.GetStreamStatsResponse.stats:type_name -> synclog.v1.StreamStats
	4,  // 9: synclog.v1.SyncLogAdminService.CreateStream:input_type -> synclog.v1.CreateStreamRequest
	6,  // 10: synclog.v1.SyncLogAdminService.DeleteStream:input_type -> synclog.v1.DeleteStreamRequest
	8,  // 11: synclog.v1.SyncLogAdminService.ListStreams:input_type -> synclog.v1.ListStreamsRequest
	10, // 12: synclog.v1.SyncLogAdminService.TruncateStream:input_type -> synclog.v1.TruncateStreamRequest
	12, // 13: synclog.v1.SyncLogAdminService.CompactStream:input_type -> synclog.v1.CompactStreamRequest
	14, // 14: synclog.v1.SyncLogAdminService.SetStreamRetention:input_type -> synclog.v1.SetStreamRetentionRequest
	16, // 15: synclog.v1.SyncLogAdminService.ResetCursor:input_type -> synclog.v1.ResetCursorRequest
	18, // 16: synclog.v1.SyncLogAdminService.ListCursors:input_type -> synclog.v1.ListCursorsRequest
	20, // 17: synclog.v1.SyncLogAdminService.GetStreamStats:input_type -> synclog.v1.GetStreamStatsRequest
	5,  // 18: synclog.v1.SyncLogAdminService.CreateStream:output_type -> synclog.v1.CreateStreamResponse
	7,  // 19: synclog.v1.SyncLogAdminService.DeleteStream:output_type -> synclog.v1.DeleteStreamResponse
	9,  // 20: synclog.v1.SyncLogAdminService.ListStreams:output_type -> synclog.v1.ListStreamsResponse
	11, // 21: synclog.v1.SyncLogAdminService.TruncateStream:output_type -> synclog.v1.TruncateStreamResponse
	13, // 22: synclog.v1.SyncLogAdminService.CompactStream:output_type -> synclog.v1.CompactStreamResponse
	15, // 23: synclog.v1.SyncLogAdminService.SetStreamRetention:output_type -> synclog.v1.SetStreamRetentionResponse
	17, // 24: synclog.v1.SyncLogAdminService.ResetCursor:output_type -> synclog.v1.ResetCursorResponse
	19, // 25: synclog.v1.SyncLogAdminService.ListCursors:output_type -> synclog.v1.ListCursorsResponse
	21, // 26: synclog.v1.SyncLogAdminService.GetStreamStats:output_type -> synclog.v1.GetStreamStatsResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_synclog_v1_admin_proto_init() }
func file_synclog_v1_admin_proto_init() {
	if File_synclog_v1_admin_proto != nil {
		return
	}
	file_synclog_v1_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synclog_v1_admin_proto_rawDesc), len(file_synclog_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synclog_v1_admin_proto_goTypes,
		DependencyIndexes: file_synclog_v1_admin_proto_depIdxs,
		EnumInfos:         file_synclog_v1_admin_proto_enumTypes,
		MessageInfos:      file_synclog_v1_admin_proto_msgTypes,
	}.Build()
	File_synclog_v1_admin_proto = out.File
	file_synclog_v1_admin_proto_goTypes = nil
	file_synclog_v1_admin_proto_depIdxs = nil
}
