// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/gateway.proto

package synclogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncGatewayService_Open_FullMethodName                     = "/synclog.v1.SyncGatewayService/Open"
	SyncGatewayService_GatewayCatchUp_FullMethodName           = "/synclog.v1.SyncGatewayService/GatewayCatchUp"
	SyncGatewayService_GatewaySubscribe_FullMethodName         = "/synclog.v1.SyncGatewayService/GatewaySubscribe"
	SyncGatewayService_GatewayAck_FullMethodName               = "/synclog.v1.SyncGatewayService/GatewayAck"
	SyncGatewayService_GatewayGetLatestSnapshot_FullMethodName = "/synclog.v1.SyncGatewayService/GatewayGetLatestSnapshot"
)

// SyncGatewayServiceClient is the client API for SyncGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncGatewayService is an embeddable, generic public sync facade over the raw
// synclog services. Product code supplies target resolution, authorization, and
// payload policy; this API keeps stream ids internal.
type SyncGatewayServiceClient interface {
	// Open resolves targets and returns their current cursor/head positions.
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	// CatchUp returns per-target batches after each target's committed cursor.
	GatewayCatchUp(ctx context.Context, in *GatewayCatchUpRequest, opts ...grpc.CallOption) (*GatewayCatchUpResponse, error)
	// Subscribe live-tails multiple targets over one stream.
	GatewaySubscribe(ctx context.Context, in *GatewaySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GatewaySubscribeResponse], error)
	// Ack advances the subscriber cursor for one target after contiguous apply.
	GatewayAck(ctx context.Context, in *GatewayAckRequest, opts ...grpc.CallOption) (*GatewayAckResponse, error)
	// GetLatestSnapshot returns the newest compatible snapshot for one target.
	GatewayGetLatestSnapshot(ctx context.Context, in *GatewayGetLatestSnapshotRequest, opts ...grpc.CallOption) (*GatewayGetLatestSnapshotResponse, error)
}

type syncGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncGatewayServiceClient(cc grpc.ClientConnInterface) SyncGatewayServiceClient {
	return &syncGatewayServiceClient{cc}
}

func (c *syncGatewayServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, SyncGatewayService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncGatewayServiceClient) GatewayCatchUp(ctx context.Context, in *GatewayCatchUpRequest, opts ...grpc.CallOption) (*GatewayCatchUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayCatchUpResponse)
	err := c.cc.Invoke(ctx, SyncGatewayService_GatewayCatchUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncGatewayServiceClient) GatewaySubscribe(ctx context.Context, in *GatewaySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GatewaySubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncGatewayService_ServiceDesc.Streams[0], SyncGatewayService_GatewaySubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewaySubscribeRequest, GatewaySubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncGatewayService_GatewaySubscribeClient = grpc.ServerStreamingClient[GatewaySubscribeResponse]

func (c *syncGatewayServiceClient) GatewayAck(ctx context.Context, in *GatewayAckRequest, opts ...grpc.CallOption) (*GatewayAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayAckResponse)
	err := c.cc.Invoke(ctx, SyncGatewayService_GatewayAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncGatewayServiceClient) GatewayGetLatestSnapshot(ctx context.Context, in *GatewayGetLatestSnapshotRequest, opts ...grpc.CallOption) (*GatewayGetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayGetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncGatewayService_GatewayGetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncGatewayServiceServer is the server API for SyncGatewayService service.
// All implementations must embed UnimplementedSyncGatewayServiceServer
// for forward compatibility.
//
// SyncGatewayService is an embeddable, generic public sync facade over the raw
// synclog services. Product code supplies target resolution, authorization, and
// payload policy; this API keeps stream ids internal.
type SyncGatewayServiceServer interface {
	// Open resolves targets and returns their current cursor/head positions.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	// CatchUp returns per-target batches after each target's committed cursor.
	GatewayCatchUp(context.Context, *GatewayCatchUpRequest) (*GatewayCatchUpResponse, error)
	// Subscribe live-tails multiple targets over one stream.
	GatewaySubscribe(*GatewaySubscribeRequest, grpc.ServerStreamingServer[GatewaySubscribeResponse]) error
	// Ack advances the subscriber cursor for one target after contiguous apply.
	GatewayAck(context.Context, *GatewayAckRequest) (*GatewayAckResponse, error)
	// GetLatestSnapshot returns the newest compatible snapshot for one target.
	GatewayGetLatestSnapshot(context.Context, *GatewayGetLatestSnapshotRequest) (*GatewayGetLatestSnapshotResponse, error)
	mustEmbedUnimplementedSyncGatewayServiceServer()
}

// UnimplementedSyncGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncGatewayServiceServer struct{}

func (UnimplementedSyncGatewayServiceServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedSyncGatewayServiceServer) GatewayCatchUp(context.Context, *GatewayCatchUpRequest) (*GatewayCatchUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GatewayCatchUp not implemented")
}
func (UnimplementedSyncGatewayServiceServer) GatewaySubscribe(*GatewaySubscribeRequest, grpc.ServerStreamingServer[GatewaySubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method GatewaySubscribe not implemented")
}
func (UnimplementedSyncGatewayServiceServer) GatewayAck(context.Context, *GatewayAckRequest) (*GatewayAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GatewayAck not implemented")
}
func (UnimplementedSyncGatewayServiceServer) GatewayGetLatestSnapshot(context.Context, *GatewayGetLatestSnapshotRequest) (*GatewayGetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GatewayGetLatestSnapshot not implemented")
}
func (UnimplementedSyncGatewayServiceServer) mustEmbedUnimplementedSyncGatewayServiceServer() {}
func (UnimplementedSyncGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeSyncGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncGatewayServiceServer will
// result in compilation errors.
type UnsafeSyncGatewayServiceServer interface {
	mustEmbedUnimplementedSyncGatewayServiceServer()
}

func RegisterSyncGatewayServiceServer(s grpc.ServiceRegistrar, srv SyncGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncGatewayService_ServiceDesc, srv)
}

func _SyncGatewayService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncGatewayServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncGatewayService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncGatewayServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncGatewayService_GatewayCatchUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayCatchUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncGatewayServiceServer).GatewayCatchUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncGatewayService_GatewayCatchUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncGatewayServiceServer).GatewayCatchUp(ctx, req.(*GatewayCatchUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncGatewayService_GatewaySubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GatewaySubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncGatewayServiceServer).GatewaySubscribe(m, &grpc.GenericServerStream[GatewaySubscribeRequest, GatewaySubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncGatewayService_GatewaySubscribeServer = grpc.ServerStreamingServer[GatewaySubscribeResponse]

func _SyncGatewayService_GatewayAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncGatewayServiceServer).GatewayAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncGatewayService_GatewayAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncGatewayServiceServer).GatewayAck(ctx, req.(*GatewayAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncGatewayService_GatewayGetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayGetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncGatewayServiceServer).GatewayGetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncGatewayService_GatewayGetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncGatewayServiceServer).GatewayGetLatestSnapshot(ctx, req.(*GatewayGetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncGatewayService_ServiceDesc is the grpc.ServiceDesc for SyncGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synclog.v1.SyncGatewayService",
	HandlerType: (*SyncGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _SyncGatewayService_Open_Handler,
		},
		{
			MethodName: "GatewayCatchUp",
			Handler:    _SyncGatewayService_GatewayCatchUp_Handler,
		},
		{
			MethodName: "GatewayAck",
			Handler:    _SyncGatewayService_GatewayAck_Handler,
		},
		{
			MethodName: "GatewayGetLatestSnapshot",
			Handler:    _SyncGatewayService_GatewayGetLatestSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GatewaySubscribe",
			Handler:       _SyncGatewayService_GatewaySubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "synclog/v1/gateway.proto",
}
