// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/gateway.proto

package synclogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncTarget is the public/product-facing address of a syncable entity. The
// product embedding the gateway resolves it to one or more internal streams and
// allowed payload types. Clients do not need to know stream ids or sharding.
type SyncTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	View          string                 `protobuf:"bytes,3,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTarget) Reset() {
	*x = SyncTarget{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTarget) ProtoMessage() {}

func (x *SyncTarget) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTarget.ProtoReflect.Descriptor instead.
func (*SyncTarget) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SyncTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SyncTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncTarget) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

// TargetBindingState is the public cursor state for one resolved binding within
// a target. `binding_key` is product-defined and stable for this target; it is
// not the internal stream id.
type TargetBindingState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BindingKey       string                 `protobuf:"bytes,1,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	CursorSeq        uint64                 `protobuf:"varint,2,opt,name=cursor_seq,json=cursorSeq,proto3" json:"cursor_seq,omitempty"`
	HeadSeq          uint64                 `protobuf:"varint,3,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	RetainedSeqStart uint64                 `protobuf:"varint,4,opt,name=retained_seq_start,json=retainedSeqStart,proto3" json:"retained_seq_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetBindingState) Reset() {
	*x = TargetBindingState{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetBindingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetBindingState) ProtoMessage() {}

func (x *TargetBindingState) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetBindingState.ProtoReflect.Descriptor instead.
func (*TargetBindingState) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *TargetBindingState) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

func (x *TargetBindingState) GetCursorSeq() uint64 {
	if x != nil {
		return x.CursorSeq
	}
	return 0
}

func (x *TargetBindingState) GetHeadSeq() uint64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *TargetBindingState) GetRetainedSeqStart() uint64 {
	if x != nil {
		return x.RetainedSeqStart
	}
	return 0
}

// TargetState exposes the committed cursor and current head for one target after
// product-side resolution and authorization.
type TargetState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target *SyncTarget            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Legacy aggregate fields for single-binding targets. For multi-binding
	// targets, inspect `bindings`.
	CursorSeq        uint64                `protobuf:"varint,2,opt,name=cursor_seq,json=cursorSeq,proto3" json:"cursor_seq,omitempty"`
	HeadSeq          uint64                `protobuf:"varint,3,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	RetainedSeqStart uint64                `protobuf:"varint,4,opt,name=retained_seq_start,json=retainedSeqStart,proto3" json:"retained_seq_start,omitempty"`
	Bindings         []*TargetBindingState `protobuf:"bytes,5,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetState) Reset() {
	*x = TargetState{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetState) ProtoMessage() {}

func (x *TargetState) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetState.ProtoReflect.Descriptor instead.
func (*TargetState) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *TargetState) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TargetState) GetCursorSeq() uint64 {
	if x != nil {
		return x.CursorSeq
	}
	return 0
}

func (x *TargetState) GetHeadSeq() uint64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *TargetState) GetRetainedSeqStart() uint64 {
	if x != nil {
		return x.RetainedSeqStart
	}
	return 0
}

func (x *TargetState) GetBindings() []*TargetBindingState {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// GatewayEvent is a public event envelope. The payload is still opaque to the
// gateway core; product hooks decide which target/payload types may be exposed.
type GatewayEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Target          *SyncTarget            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq             uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadType     string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion  uint32                 `protobuf:"varint,5,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	BindingKey      string                 `protobuf:"bytes,7,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayEvent) Reset() {
	*x = GatewayEvent{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEvent) ProtoMessage() {}

func (x *GatewayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEvent.ProtoReflect.Descriptor instead.
func (*GatewayEvent) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayEvent) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewayEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GatewayEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayEvent) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *GatewayEvent) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

func (x *GatewayEvent) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *GatewayEvent) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewayBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *SyncTarget            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Events        []*GatewayEvent        `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	SeqStart      uint64                 `protobuf:"varint,3,opt,name=seq_start,json=seqStart,proto3" json:"seq_start,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Final         bool                   `protobuf:"varint,5,opt,name=final,proto3" json:"final,omitempty"`
	BindingKey    string                 `protobuf:"bytes,6,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayBatch) Reset() {
	*x = GatewayBatch{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayBatch) ProtoMessage() {}

func (x *GatewayBatch) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayBatch.ProtoReflect.Descriptor instead.
func (*GatewayBatch) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayBatch) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewayBatch) GetEvents() []*GatewayEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GatewayBatch) GetSeqStart() uint64 {
	if x != nil {
		return x.SeqStart
	}
	return 0
}

func (x *GatewayBatch) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GatewayBatch) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *GatewayBatch) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewaySnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Target         *SyncTarget            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadType    string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion uint32                 `protobuf:"varint,5,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	Compression    SnapshotCompression    `protobuf:"varint,6,opt,name=compression,proto3,enum=synclog.v1.SnapshotCompression" json:"compression,omitempty"`
	Checksum       string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	BindingKey     string                 `protobuf:"bytes,8,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewaySnapshot) Reset() {
	*x = GatewaySnapshot{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySnapshot) ProtoMessage() {}

func (x *GatewaySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySnapshot.ProtoReflect.Descriptor instead.
func (*GatewaySnapshot) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewaySnapshot) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewaySnapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GatewaySnapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewaySnapshot) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *GatewaySnapshot) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

func (x *GatewaySnapshot) GetCompression() SnapshotCompression {
	if x != nil {
		return x.Compression
	}
	return SnapshotCompression_SNAPSHOT_COMPRESSION_NONE
}

func (x *GatewaySnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *GatewaySnapshot) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Targets       []*SyncTarget          `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *OpenRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *OpenRequest) GetTargets() []*SyncTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*TargetState         `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *OpenResponse) GetTargets() []*TargetState {
	if x != nil {
		return x.Targets
	}
	return nil
}

type GatewayCatchUpRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId        string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Targets             []*SyncTarget          `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	LimitPerTarget      uint32                 `protobuf:"varint,3,opt,name=limit_per_target,json=limitPerTarget,proto3" json:"limit_per_target,omitempty"`
	TotalLimitPerTarget uint32                 `protobuf:"varint,4,opt,name=total_limit_per_target,json=totalLimitPerTarget,proto3" json:"total_limit_per_target,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GatewayCatchUpRequest) Reset() {
	*x = GatewayCatchUpRequest{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCatchUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCatchUpRequest) ProtoMessage() {}

func (x *GatewayCatchUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCatchUpRequest.ProtoReflect.Descriptor instead.
func (*GatewayCatchUpRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayCatchUpRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *GatewayCatchUpRequest) GetTargets() []*SyncTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *GatewayCatchUpRequest) GetLimitPerTarget() uint32 {
	if x != nil {
		return x.LimitPerTarget
	}
	return 0
}

func (x *GatewayCatchUpRequest) GetTotalLimitPerTarget() uint32 {
	if x != nil {
		return x.TotalLimitPerTarget
	}
	return 0
}

type GatewayCatchUpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *SyncTarget            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Status        CatchUpStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=synclog.v1.CatchUpStatus" json:"status,omitempty"`
	Batch         *GatewayBatch          `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	State         *TargetState           `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	BindingKey    string                 `protobuf:"bytes,5,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCatchUpResult) Reset() {
	*x = GatewayCatchUpResult{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCatchUpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCatchUpResult) ProtoMessage() {}

func (x *GatewayCatchUpResult) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCatchUpResult.ProtoReflect.Descriptor instead.
func (*GatewayCatchUpResult) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayCatchUpResult) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewayCatchUpResult) GetStatus() CatchUpStatus {
	if x != nil {
		return x.Status
	}
	return CatchUpStatus_CATCH_UP_STATUS_NONE
}

func (x *GatewayCatchUpResult) GetBatch() *GatewayBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *GatewayCatchUpResult) GetState() *TargetState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GatewayCatchUpResult) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewayCatchUpResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*GatewayCatchUpResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCatchUpResponse) Reset() {
	*x = GatewayCatchUpResponse{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCatchUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCatchUpResponse) ProtoMessage() {}

func (x *GatewayCatchUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCatchUpResponse.ProtoReflect.Descriptor instead.
func (*GatewayCatchUpResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayCatchUpResponse) GetResults() []*GatewayCatchUpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GatewaySubscribeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId         string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Targets              []*SyncTarget          `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	BatchLimitPerTarget  uint32                 `protobuf:"varint,3,opt,name=batch_limit_per_target,json=batchLimitPerTarget,proto3" json:"batch_limit_per_target,omitempty"`
	MaxInFlightPerTarget uint32                 `protobuf:"varint,4,opt,name=max_in_flight_per_target,json=maxInFlightPerTarget,proto3" json:"max_in_flight_per_target,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GatewaySubscribeRequest) Reset() {
	*x = GatewaySubscribeRequest{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySubscribeRequest) ProtoMessage() {}

func (x *GatewaySubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySubscribeRequest.ProtoReflect.Descriptor instead.
func (*GatewaySubscribeRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *GatewaySubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *GatewaySubscribeRequest) GetTargets() []*SyncTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *GatewaySubscribeRequest) GetBatchLimitPerTarget() uint32 {
	if x != nil {
		return x.BatchLimitPerTarget
	}
	return 0
}

func (x *GatewaySubscribeRequest) GetMaxInFlightPerTarget() uint32 {
	if x != nil {
		return x.MaxInFlightPerTarget
	}
	return 0
}

type GatewaySubscribeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           CatchUpStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=synclog.v1.CatchUpStatus" json:"status,omitempty"`
	Batch            *GatewayBatch          `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	State            *TargetState           `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Heartbeat        bool                   `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	ServerTimeUnixMs int64                  `protobuf:"varint,5,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	BindingKey       string                 `protobuf:"bytes,6,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatewaySubscribeResponse) Reset() {
	*x = GatewaySubscribeResponse{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySubscribeResponse) ProtoMessage() {}

func (x *GatewaySubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySubscribeResponse.ProtoReflect.Descriptor instead.
func (*GatewaySubscribeResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *GatewaySubscribeResponse) GetStatus() CatchUpStatus {
	if x != nil {
		return x.Status
	}
	return CatchUpStatus_CATCH_UP_STATUS_NONE
}

func (x *GatewaySubscribeResponse) GetBatch() *GatewayBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *GatewaySubscribeResponse) GetState() *TargetState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GatewaySubscribeResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *GatewaySubscribeResponse) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *GatewaySubscribeResponse) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewayAckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Target        *SyncTarget            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BindingKey    string                 `protobuf:"bytes,5,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayAckRequest) Reset() {
	*x = GatewayAckRequest{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAckRequest) ProtoMessage() {}

func (x *GatewayAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAckRequest.ProtoReflect.Descriptor instead.
func (*GatewayAckRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *GatewayAckRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *GatewayAckRequest) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewayAckRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GatewayAckRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *GatewayAckRequest) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewayAckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TargetState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayAckResponse) Reset() {
	*x = GatewayAckResponse{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAckResponse) ProtoMessage() {}

func (x *GatewayAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAckResponse.ProtoReflect.Descriptor instead.
func (*GatewayAckResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *GatewayAckResponse) GetState() *TargetState {
	if x != nil {
		return x.State
	}
	return nil
}

type GatewayGetLatestSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId      string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Target            *SyncTarget            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	PayloadType       string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	MaxPayloadVersion uint32                 `protobuf:"varint,4,opt,name=max_payload_version,json=maxPayloadVersion,proto3" json:"max_payload_version,omitempty"`
	BindingKey        string                 `protobuf:"bytes,5,opt,name=binding_key,json=bindingKey,proto3" json:"binding_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayGetLatestSnapshotRequest) Reset() {
	*x = GatewayGetLatestSnapshotRequest{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayGetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayGetLatestSnapshotRequest) ProtoMessage() {}

func (x *GatewayGetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayGetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GatewayGetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *GatewayGetLatestSnapshotRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *GatewayGetLatestSnapshotRequest) GetTarget() *SyncTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GatewayGetLatestSnapshotRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *GatewayGetLatestSnapshotRequest) GetMaxPayloadVersion() uint32 {
	if x != nil {
		return x.MaxPayloadVersion
	}
	return 0
}

func (x *GatewayGetLatestSnapshotRequest) GetBindingKey() string {
	if x != nil {
		return x.BindingKey
	}
	return ""
}

type GatewayGetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *GatewaySnapshot       `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	State         *TargetState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayGetLatestSnapshotResponse) Reset() {
	*x = GatewayGetLatestSnapshotResponse{}
	mi := &file_synclog_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayGetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayGetLatestSnapshotResponse) ProtoMessage() {}

func (x *GatewayGetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayGetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GatewayGetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *GatewayGetLatestSnapshotResponse) GetSnapshot() *GatewaySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GatewayGetLatestSnapshotResponse) GetState() *TargetState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_synclog_v1_gateway_proto protoreflect.FileDescriptor

const file_synclog_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18synclog/v1/gateway.proto\x12\n" +
	"synclog.v1\x1a\x18synclog/v1/service.proto\x1a\x19synclog/v1/snapshot.proto\"N\n" +
	"\n" +
	"SyncTarget\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04view\x18\x03 \x01(\tR\x04view\"\x9d\x01\n" +
	"\x12TargetBindingState\x12\x1f\n" +
	"\vbinding_key\x18\x01 \x01(\tR\n" +
	"bindingKey\x12\x1d\n" +
	"\n" +
	"cursor_seq\x18\x02 \x01(\x04R\tcursorSeq\x12\x19\n" +
	"\bhead_seq\x18\x03 \x01(\x04R\aheadSeq\x12,\n" +
	"\x12retained_seq_start\x18\x04 \x01(\x04R\x10retainedSeqStart\"\xe1\x01\n" +
	"\vTargetState\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x12\x1d\n" +
	"\n" +
	"cursor_seq\x18\x02 \x01(\x04R\tcursorSeq\x12\x19\n" +
	"\bhead_seq\x18\x03 \x01(\x04R\aheadSeq\x12,\n" +
	"\x12retained_seq_start\x18\x04 \x01(\x04R\x10retainedSeqStart\x12:\n" +
	"\bbindings\x18\x05 \x03(\v2\x1e.synclog.v1.TargetBindingStateR\bbindings\"\x84\x02\n" +
	"\fGatewayEvent\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x05 \x01(\rR\x0epayloadVersion\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs\x12\x1f\n" +
	"\vbinding_key\x18\a \x01(\tR\n" +
	"bindingKey\"\xd6\x01\n" +
	"\fGatewayBatch\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.synclog.v1.GatewayEventR\x06events\x12\x1b\n" +
	"\tseq_start\x18\x03 \x01(\x04R\bseqStart\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05final\x18\x05 \x01(\bR\x05final\x12\x1f\n" +
	"\vbinding_key\x18\x06 \x01(\tR\n" +
	"bindingKey\"\xb9\x02\n" +
	"\x0fGatewaySnapshot\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x05 \x01(\rR\x0epayloadVersion\x12A\n" +
	"\vcompression\x18\x06 \x01(\x0e2\x1f.synclog.v1.SnapshotCompressionR\vcompression\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1f\n" +
	"\vbinding_key\x18\b \x01(\tR\n" +
	"bindingKey\"d\n" +
	"\vOpenRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x120\n" +
	"\atargets\x18\x02 \x03(\v2\x16.synclog.v1.SyncTargetR\atargets\"A\n" +
	"\fOpenResponse\x121\n" +
	"\atargets\x18\x01 \x03(\v2\x17.synclog.v1.TargetStateR\atargets\"\xcd\x01\n" +
	"\x15GatewayCatchUpRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x120\n" +
	"\atargets\x18\x02 \x03(\v2\x16.synclog.v1.SyncTargetR\atargets\x12(\n" +
	"\x10limit_per_target\x18\x03 \x01(\rR\x0elimitPerTarget\x123\n" +
	"\x16total_limit_per_target\x18\x04 \x01(\rR\x13totalLimitPerTarget\"\xf9\x01\n" +
	"\x14GatewayCatchUpResult\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.synclog.v1.CatchUpStatusR\x06status\x12.\n" +
	"\x05batch\x18\x03 \x01(\v2\x18.synclog.v1.GatewayBatchR\x05batch\x12-\n" +
	"\x05state\x18\x04 \x01(\v2\x17.synclog.v1.TargetStateR\x05state\x12\x1f\n" +
	"\vbinding_key\x18\x05 \x01(\tR\n" +
	"bindingKey\"T\n" +
	"\x16GatewayCatchUpResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .synclog.v1.GatewayCatchUpResultR\aresults\"\xdd\x01\n" +
	"\x17GatewaySubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x120\n" +
	"\atargets\x18\x02 \x03(\v2\x16.synclog.v1.SyncTargetR\atargets\x123\n" +
	"\x16batch_limit_per_target\x18\x03 \x01(\rR\x13batchLimitPerTarget\x126\n" +
	"\x18max_in_flight_per_target\x18\x04 \x01(\rR\x14maxInFlightPerTarget\"\x9a\x02\n" +
	"\x18GatewaySubscribeResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.synclog.v1.CatchUpStatusR\x06status\x12.\n" +
	"\x05batch\x18\x02 \x01(\v2\x18.synclog.v1.GatewayBatchR\x05batch\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.synclog.v1.TargetStateR\x05state\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\bR\theartbeat\x12-\n" +
	"\x13server_time_unix_ms\x18\x05 \x01(\x03R\x10serverTimeUnixMs\x12\x1f\n" +
	"\vbinding_key\x18\x06 \x01(\tR\n" +
	"bindingKey\"\xb7\x01\n" +
	"\x11GatewayAckRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x1f\n" +
	"\vbinding_key\x18\x05 \x01(\tR\n" +
	"bindingKey\"C\n" +
	"\x12GatewayAckResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.synclog.v1.TargetStateR\x05state\"\xea\x01\n" +
	"\x1fGatewayGetLatestSnapshotRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.synclog.v1.SyncTargetR\x06target\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\tR\vpayloadType\x12.\n" +
	"\x13max_payload_version\x18\x04 \x01(\rR\x11maxPayloadVersion\x12\x1f\n" +
	"\vbinding_key\x18\x05 \x01(\tR\n" +
	"bindingKey\"\x8a\x01\n" +
	" GatewayGetLatestSnapshotResponse\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.synclog.v1.GatewaySnapshotR\bsnapshot\x12-\n" +
	"\x05state\x18\x02 \x01(\v2\x17.synclog.v1.TargetStateR\x05state2\xcd\x03\n" +
	"\x12SyncGatewayService\x129\n" +
	"\x04Open\x12\x17.synclog.v1.OpenRequest\x1a\x18.synclog.v1.OpenResponse\x12W\n" +
	"\x0eGatewayCatchUp\x12!.synclog.v1.GatewayCatchUpRequest\x1a\".synclog.v1.GatewayCatchUpResponse\x12_\n" +
	"\x10GatewaySubscribe\x12#.synclog.v1.GatewaySubscribeRequest\x1a$.synclog.v1.GatewaySubscribeResponse0\x01\x12K\n" +
	"\n" +
	"GatewayAck\x12\x1d.synclog.v1.GatewayAckRequest\x1a\x1e.synclog.v1.GatewayAckResponse\x12u\n" +
	"\x18GatewayGetLatestSnapshot\x12+.synclog.v1.GatewayGetLatestSnapshotRequest\x1a,.synclog.v1.GatewayGetLatestSnapshotResponseB<Z:github.com/gopherex/synclog/pkg/proto/synclog/v1;synclogv1b\x06proto3"

var (
	file_synclog_v1_gateway_proto_rawDescOnce sync.Once
	file_synclog_v1_gateway_proto_rawDescData []byte
)

func file_synclog_v1_gateway_proto_rawDescGZIP() []byte {
	file_synclog_v1_gateway_proto_rawDescOnce.Do(func() {
		file_synclog_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synclog_v1_gateway_proto_rawDesc), len(file_synclog_v1_gateway_proto_rawDesc)))
	})
	return file_synclog_v1_gateway_proto_rawDescData
}

var file_synclog_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_synclog_v1_gateway_proto_goTypes = []any{
	(*SyncTarget)(nil),                       // 0: synclog.v1.SyncTarget
	(*TargetBindingState)(nil),               // 1: synclog.v1.TargetBindingState
	(*TargetState)(nil),                      // 2: synclog.v1.TargetState
	(*GatewayEvent)(nil),                     // 3: synclog.v1.GatewayEvent
	(*GatewayBatch)(nil),                     // 4: synclog.v1.GatewayBatch
	(*GatewaySnapshot)(nil),                  // 5: synclog.v1.GatewaySnapshot
	(*OpenRequest)(nil),                      // 6: synclog.v1.OpenRequest
	(*OpenResponse)(nil),                     // 7: synclog.v1.OpenResponse
	(*GatewayCatchUpRequest)(nil),            // 8: synclog.v1.GatewayCatchUpRequest
	(*GatewayCatchUpResult)(nil),             // 9: synclog.v1.GatewayCatchUpResult
	(*GatewayCatchUpResponse)(nil),           // 10: synclog.v1.GatewayCatchUpResponse
	(*GatewaySubscribeRequest)(nil),          // 11: synclog.v1.GatewaySubscribeRequest
	(*GatewaySubscribeResponse)(nil),         // 12: synclog.v1.GatewaySubscribeResponse
	(*GatewayAckRequest)(nil),                // 13: synclog.v1.GatewayAckRequest
	(*GatewayAckResponse)(nil),               // 14: synclog.v1.GatewayAckResponse
	(*GatewayGetLatestSnapshotRequest)(nil),  // 15: synclog.v1.GatewayGetLatestSnapshotRequest
	(*GatewayGetLatestSnapshotResponse)(nil), // 16: synclog.v1.GatewayGetLatestSnapshotResponse
	(SnapshotCompression)(0),                 // 17: synclog.v1.SnapshotCompression
	(CatchUpStatus)(0),                       // 18: synclog.v1.CatchUpStatus
}
var file_synclog_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: synclog.v1.TargetState.target:type_name -> synclog.v1.SyncTarget
	1,  // 1: synclog.v1.TargetState.bindings:type_name -> synclog.v1.TargetBindingState
	0,  // 2: synclog.v1.GatewayEvent.target:type_name -> synclog.v1.SyncTarget
	0,  // 3: synclog.v1.GatewayBatch.target:type_name -> synclog.v1.SyncTarget
	3,  // 4: synclog.v1.GatewayBatch.events:type_name -> synclog.v1.GatewayEvent
	0,  // 5: synclog.v1.GatewaySnapshot.target:type_name -> synclog.v1.SyncTarget
	17, // 6: synclog.v1.GatewaySnapshot.compression:type_name -> synclog.v1.SnapshotCompression
	0,  // 7: synclog.v1.OpenRequest.targets:type_name -> synclog.v1.SyncTarget
	2,  // 8: synclog.v1.OpenResponse.targets:type_name -> synclog.v1.TargetState
	0,  // 9: synclog.v1.GatewayCatchUpRequest.targets:type_name -> synclog.v1.SyncTarget
	0,  // 10: synclog.v1.GatewayCatchUpResult.target:type_name -> synclog.v1.SyncTarget
	18, // 11: synclog.v1.GatewayCatchUpResult.status:type_name -> synclog.v1.CatchUpStatus
	4,  // 12: synclog.v1.GatewayCatchUpResult.batch:type_name -> synclog.v1.GatewayBatch
	2,  // 13: synclog.v1.GatewayCatchUpResult.state:type_name -> synclog.v1.TargetState
	9,  // 14: synclog.v1.GatewayCatchUpResponse.results:type_name -> synclog.v1.GatewayCatchUpResult
	0,  // 15: synclog.v1.GatewaySubscribeRequest.targets:type_name -> synclog.v1.SyncTarget
	18, // 16: synclog.v1.GatewaySubscribeResponse.status:type_name -> synclog.v1.CatchUpStatus
	4,  // 17: synclog.v1.GatewaySubscribeResponse.batch:type_name -> synclog.v1.GatewayBatch
	2,  // 18: synclog.v1.GatewaySubscribeResponse.state:type_name -> synclog.v1.TargetState
	0,  // 19: synclog.v1.GatewayAckRequest.target:type_name -> synclog.v1.SyncTarget
	2,  // 20: synclog.v1.GatewayAckResponse.state:type_name -> synclog.v1.TargetState
	0,  // 21: synclog.v1.GatewayGetLatestSnapshotRequest.target:type_name -> synclog.v1.SyncTarget
	5,  // 22: synclog.v1.GatewayGetLatestSnapshotResponse.snapshot:type_name -> synclog.v1.GatewaySnapshot
	2,  // 23: synclog.v1.GatewayGetLatestSnapshotResponse.state:type_name -> synclog.v1.TargetState
	6,  // 24: synclog.v1.SyncGatewayService.Open:input_type -> synclog.v1.OpenRequest
	8,  // 25: synclog.v1.SyncGatewayService.GatewayCatchUp:input_type -> synclog.v1.GatewayCatchUpRequest
	11, // 26: synclog.v1.SyncGatewayService.GatewaySubscribe:input_type -> synclog.v1.GatewaySubscribeRequest
	13, // 27: synclog.v1.SyncGatewayService.GatewayAck:input_type -> synclog.v1.GatewayAckRequest
	15, // 28: synclog.v1.SyncGatewayService.GatewayGetLatestSnapshot:input_type -> synclog.v1.GatewayGetLatestSnapshotRequest
	7,  // 29: synclog.v1.SyncGatewayService.Open:output_type -> synclog.v1.OpenResponse
	10, // 30: synclog.v1.SyncGatewayService.GatewayCatchUp:output_type -> synclog.v1.GatewayCatchUpResponse
	12, // 31: synclog.v1.SyncGatewayService.GatewaySubscribe:output_type -> synclog.v1.GatewaySubscribeResponse
	14, // 32: synclog.v1.SyncGatewayService.GatewayAck:output_type -> synclog.v1.GatewayAckResponse
	16, // 33: synclog.v1.SyncGatewayService.GatewayGetLatestSnapshot:output_type -> synclog.v1.GatewayGetLatestSnapshotResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_synclog_v1_gateway_proto_init() }
func file_synclog_v1_gateway_proto_init() {
	if File_synclog_v1_gateway_proto != nil {
		return
	}
	file_synclog_v1_service_proto_init()
	file_synclog_v1_snapshot_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synclog_v1_gateway_proto_rawDesc), len(file_synclog_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synclog_v1_gateway_proto_goTypes,
		DependencyIndexes: file_synclog_v1_gateway_proto_depIdxs,
		MessageInfos:      file_synclog_v1_gateway_proto_msgTypes,
	}.Build()
	File_synclog_v1_gateway_proto = out.File
	file_synclog_v1_gateway_proto_goTypes = nil
	file_synclog_v1_gateway_proto_depIdxs = nil
}
