// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/service.proto

package synclogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatchUpStatus int32

const (
	CatchUpStatus_CATCH_UP_STATUS_NONE CatchUpStatus = 0
	CatchUpStatus_CATCH_UP_STATUS_OK   CatchUpStatus = 1
	// The committed cursor is behind the retained log, or the requested total
	// limit would be exceeded. The consumer must refresh from a higher-level
	// source of truth and then Ack the snapshot seq.
	CatchUpStatus_CATCH_UP_STATUS_TOO_LONG CatchUpStatus = 2
)

// Enum value maps for CatchUpStatus.
var (
	CatchUpStatus_name = map[int32]string{
		0: "CATCH_UP_STATUS_NONE",
		1: "CATCH_UP_STATUS_OK",
		2: "CATCH_UP_STATUS_TOO_LONG",
	}
	CatchUpStatus_value = map[string]int32{
		"CATCH_UP_STATUS_NONE":     0,
		"CATCH_UP_STATUS_OK":       1,
		"CATCH_UP_STATUS_TOO_LONG": 2,
	}
)

func (x CatchUpStatus) Enum() *CatchUpStatus {
	p := new(CatchUpStatus)
	*p = x
	return p
}

func (x CatchUpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatchUpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_synclog_v1_service_proto_enumTypes[0].Descriptor()
}

func (CatchUpStatus) Type() protoreflect.EnumType {
	return &file_synclog_v1_service_proto_enumTypes[0]
}

func (x CatchUpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatchUpStatus.Descriptor instead.
func (CatchUpStatus) EnumDescriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{0}
}

type AppendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadType    string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion uint32                 `protobuf:"varint,4,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AppendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *AppendRequest) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

func (x *AppendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AppendResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadRequest) Reset() {
	*x = GetHeadRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadRequest) ProtoMessage() {}

func (x *GetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadRequest.ProtoReflect.Descriptor instead.
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetHeadRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetHeadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Head  *Cursor                `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// First retained seq in the stream. If a subscriber cursor is below this
	// value, CatchUp returns CATCH_UP_STATUS_TOO_LONG.
	RetainedSeqStart uint64 `protobuf:"varint,2,opt,name=retained_seq_start,json=retainedSeqStart,proto3" json:"retained_seq_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHeadResponse) Reset() {
	*x = GetHeadResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadResponse) ProtoMessage() {}

func (x *GetHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadResponse.ProtoReflect.Descriptor instead.
func (*GetHeadResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetHeadResponse) GetHead() *Cursor {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetHeadResponse) GetRetainedSeqStart() uint64 {
	if x != nil {
		return x.RetainedSeqStart
	}
	return 0
}

type GetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursorRequest) Reset() {
	*x = GetCursorRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursorRequest) ProtoMessage() {}

func (x *GetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursorRequest.ProtoReflect.Descriptor instead.
func (*GetCursorRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCursorRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *GetCursorRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *Cursor                `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Head          *Cursor                `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursorResponse) Reset() {
	*x = GetCursorResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursorResponse) ProtoMessage() {}

func (x *GetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursorResponse.ProtoReflect.Descriptor instead.
func (*GetCursorResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCursorResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *GetCursorResponse) GetHead() *Cursor {
	if x != nil {
		return x.Head
	}
	return nil
}

type CatchUpRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	StreamId     string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Max events to return; server may return fewer and set final=false.
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// If set and committed cursor + total_limit < head, the server returns
	// CATCH_UP_STATUS_TOO_LONG instead of a large catch-up.
	TotalLimit    uint32 `protobuf:"varint,4,opt,name=total_limit,json=totalLimit,proto3" json:"total_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchUpRequest) Reset() {
	*x = CatchUpRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpRequest) ProtoMessage() {}

func (x *CatchUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpRequest.ProtoReflect.Descriptor instead.
func (*CatchUpRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CatchUpRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *CatchUpRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CatchUpRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CatchUpRequest) GetTotalLimit() uint32 {
	if x != nil {
		return x.TotalLimit
	}
	return 0
}

type CatchUpResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           CatchUpStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=synclog.v1.CatchUpStatus" json:"status,omitempty"`
	Batch            *EventBatch            `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	Cursor           *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Head             *Cursor                `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	RetainedSeqStart uint64                 `protobuf:"varint,5,opt,name=retained_seq_start,json=retainedSeqStart,proto3" json:"retained_seq_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatchUpResponse) Reset() {
	*x = CatchUpResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpResponse) ProtoMessage() {}

func (x *CatchUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpResponse.ProtoReflect.Descriptor instead.
func (*CatchUpResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CatchUpResponse) GetStatus() CatchUpStatus {
	if x != nil {
		return x.Status
	}
	return CatchUpStatus_CATCH_UP_STATUS_NONE
}

func (x *CatchUpResponse) GetBatch() *EventBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *CatchUpResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *CatchUpResponse) GetHead() *Cursor {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *CatchUpResponse) GetRetainedSeqStart() uint64 {
	if x != nil {
		return x.RetainedSeqStart
	}
	return 0
}

type SubscribeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	StreamId     string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Max events per streamed batch.
	BatchLimit uint32 `protobuf:"varint,3,opt,name=batch_limit,json=batchLimit,proto3" json:"batch_limit,omitempty"`
	// Server-side flow-control hint: pause delivery when this many events are
	// delivered but not yet Acked.
	MaxInFlight   uint32 `protobuf:"varint,4,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SubscribeRequest) GetBatchLimit() uint32 {
	if x != nil {
		return x.BatchLimit
	}
	return 0
}

func (x *SubscribeRequest) GetMaxInFlight() uint32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

type SubscribeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           CatchUpStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=synclog.v1.CatchUpStatus" json:"status,omitempty"`
	Batch            *EventBatch            `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	Cursor           *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Head             *Cursor                `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	RetainedSeqStart uint64                 `protobuf:"varint,5,opt,name=retained_seq_start,json=retainedSeqStart,proto3" json:"retained_seq_start,omitempty"`
	// True for an idle keepalive frame. Heartbeat responses carry no batch.
	Heartbeat        bool  `protobuf:"varint,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	ServerTimeUnixMs int64 `protobuf:"varint,7,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeResponse) GetStatus() CatchUpStatus {
	if x != nil {
		return x.Status
	}
	return CatchUpStatus_CATCH_UP_STATUS_NONE
}

func (x *SubscribeResponse) GetBatch() *EventBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *SubscribeResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SubscribeResponse) GetHead() *Cursor {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *SubscribeResponse) GetRetainedSeqStart() uint64 {
	if x != nil {
		return x.RetainedSeqStart
	}
	return 0
}

func (x *SubscribeResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *SubscribeResponse) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_synclog_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *AckRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *AckRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AckRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AckRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *Cursor                `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Head          *Cursor                `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_synclog_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *AckResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *AckResponse) GetHead() *Cursor {
	if x != nil {
		return x.Head
	}
	return nil
}

var File_synclog_v1_service_proto protoreflect.FileDescriptor

const file_synclog_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18synclog/v1/service.proto\x12\n" +
	"synclog.v1\x1a\x16synclog/v1/event.proto\"\xbb\x01\n" +
	"\rAppendRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\tR\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x04 \x01(\rR\x0epayloadVersion\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"F\n" +
	"\x0eAppendResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"-\n" +
	"\x0eGetHeadRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"g\n" +
	"\x0fGetHeadResponse\x12&\n" +
	"\x04head\x18\x01 \x01(\v2\x12.synclog.v1.CursorR\x04head\x12,\n" +
	"\x12retained_seq_start\x18\x02 \x01(\x04R\x10retainedSeqStart\"T\n" +
	"\x10GetCursorRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"g\n" +
	"\x11GetCursorResponse\x12*\n" +
	"\x06cursor\x18\x01 \x01(\v2\x12.synclog.v1.CursorR\x06cursor\x12&\n" +
	"\x04head\x18\x02 \x01(\v2\x12.synclog.v1.CursorR\x04head\"\x89\x01\n" +
	"\x0eCatchUpRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1f\n" +
	"\vtotal_limit\x18\x04 \x01(\rR\n" +
	"totalLimit\"\xf4\x01\n" +
	"\x0fCatchUpResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.synclog.v1.CatchUpStatusR\x06status\x12,\n" +
	"\x05batch\x18\x02 \x01(\v2\x16.synclog.v1.EventBatchR\x05batch\x12*\n" +
	"\x06cursor\x18\x03 \x01(\v2\x12.synclog.v1.CursorR\x06cursor\x12&\n" +
	"\x04head\x18\x04 \x01(\v2\x12.synclog.v1.CursorR\x04head\x12,\n" +
	"\x12retained_seq_start\x18\x05 \x01(\x04R\x10retainedSeqStart\"\x99\x01\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vbatch_limit\x18\x03 \x01(\rR\n" +
	"batchLimit\x12\"\n" +
	"\rmax_in_flight\x18\x04 \x01(\rR\vmaxInFlight\"\xc3\x02\n" +
	"\x11SubscribeResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.synclog.v1.CatchUpStatusR\x06status\x12,\n" +
	"\x05batch\x18\x02 \x01(\v2\x16.synclog.v1.EventBatchR\x05batch\x12*\n" +
	"\x06cursor\x18\x03 \x01(\v2\x12.synclog.v1.CursorR\x06cursor\x12&\n" +
	"\x04head\x18\x04 \x01(\v2\x12.synclog.v1.CursorR\x04head\x12,\n" +
	"\x12retained_seq_start\x18\x05 \x01(\x04R\x10retainedSeqStart\x12\x1c\n" +
	"\theartbeat\x18\x06 \x01(\bR\theartbeat\x12-\n" +
	"\x13server_time_unix_ms\x18\a \x01(\x03R\x10serverTimeUnixMs\"|\n" +
	"\n" +
	"AckRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"a\n" +
	"\vAckResponse\x12*\n" +
	"\x06cursor\x18\x01 \x01(\v2\x12.synclog.v1.CursorR\x06cursor\x12&\n" +
	"\x04head\x18\x02 \x01(\v2\x12.synclog.v1.CursorR\x04head*_\n" +
	"\rCatchUpStatus\x12\x18\n" +
	"\x14CATCH_UP_STATUS_NONE\x10\x00\x12\x16\n" +
	"\x12CATCH_UP_STATUS_OK\x10\x01\x12\x1c\n" +
	"\x18CATCH_UP_STATUS_TOO_LONG\x10\x022\xa7\x03\n" +
	"\x0eSyncLogService\x12?\n" +
	"\x06Append\x12\x19.synclog.v1.AppendRequest\x1a\x1a.synclog.v1.AppendResponse\x12B\n" +
	"\aGetHead\x12\x1a.synclog.v1.GetHeadRequest\x1a\x1b.synclog.v1.GetHeadResponse\x12H\n" +
	"\tGetCursor\x12\x1c.synclog.v1.GetCursorRequest\x1a\x1d.synclog.v1.GetCursorResponse\x12B\n" +
	"\aCatchUp\x12\x1a.synclog.v1.CatchUpRequest\x1a\x1b.synclog.v1.CatchUpResponse\x12J\n" +
	"\tSubscribe\x12\x1c.synclog.v1.SubscribeRequest\x1a\x1d.synclog.v1.SubscribeResponse0\x01\x126\n" +
	"\x03Ack\x12\x16.synclog.v1.AckRequest\x1a\x17.synclog.v1.AckResponseB<Z:github.com/gopherex/synclog/pkg/proto/synclog/v1;synclogv1b\x06proto3"

var (
	file_synclog_v1_service_proto_rawDescOnce sync.Once
	file_synclog_v1_service_proto_rawDescData []byte
)

func file_synclog_v1_service_proto_rawDescGZIP() []byte {
	file_synclog_v1_service_proto_rawDescOnce.Do(func() {
		file_synclog_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synclog_v1_service_proto_rawDesc), len(file_synclog_v1_service_proto_rawDesc)))
	})
	return file_synclog_v1_service_proto_rawDescData
}

var file_synclog_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synclog_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_synclog_v1_service_proto_goTypes = []any{
	(CatchUpStatus)(0),        // 0: synclog.v1.CatchUpStatus
	(*AppendRequest)(nil),     // 1: synclog.v1.AppendRequest
	(*AppendResponse)(nil),    // 2: synclog.v1.AppendResponse
	(*GetHeadRequest)(nil),    // 3: synclog.v1.GetHeadRequest
	(*GetHeadResponse)(nil),   // 4: synclog.v1.GetHeadResponse
	(*GetCursorRequest)(nil),  // 5: synclog.v1.GetCursorRequest
	(*GetCursorResponse)(nil), // 6: synclog.v1.GetCursorResponse
	(*CatchUpRequest)(nil),    // 7: synclog.v1.CatchUpRequest
	(*CatchUpResponse)(nil),   // 8: synclog.v1.CatchUpResponse
	(*SubscribeRequest)(nil),  // 9: synclog.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 10: synclog.v1.SubscribeResponse
	(*AckRequest)(nil),        // 11: synclog.v1.AckRequest
	(*AckResponse)(nil),       // 12: synclog.v1.AckResponse
	(*Cursor)(nil),            // 13: synclog.v1.Cursor
	(*EventBatch)(nil),        // 14: synclog.v1.EventBatch
}
var file_synclog_v1_service_proto_depIdxs = []int32{
	13, // 0: synclog.v1.GetHeadResponse.head:type_name -> synclog.v1.Cursor
	13, // 1: synclog.v1.GetCursorResponse.cursor:type_name -> synclog.v1.Cursor
	13, // 2: synclog.v1.GetCursorResponse.head:type_name -> synclog.v1.Cursor
	0,  // 3: synclog.v1.CatchUpResponse.status:type_name -> synclog.v1.CatchUpStatus
	14, // 4: synclog.v1.CatchUpResponse.batch:type_name -> synclog.v1.EventBatch
	13, // 5: synclog.v1.CatchUpResponse.cursor:type_name -> synclog.v1.Cursor
	13, // 6: synclog.v1.CatchUpResponse.head:type_name -> synclog.v1.Cursor
	0,  // 7: synclog.v1.SubscribeResponse.status:type_name -> synclog.v1.CatchUpStatus
	14, // 8: synclog.v1.SubscribeResponse.batch:type_name -> synclog.v1.EventBatch
	13, // 9: synclog.v1.SubscribeResponse.cursor:type_name -> synclog.v1.Cursor
	13, // 10: synclog.v1.SubscribeResponse.head:type_name -> synclog.v1.Cursor
	13, // 11: synclog.v1.AckResponse.cursor:type_name -> synclog.v1.Cursor
	13, // 12: synclog.v1.AckResponse.head:type_name -> synclog.v1.Cursor
	1,  // 13: synclog.v1.SyncLogService.Append:input_type -> synclog.v1.AppendRequest
	3,  // 14: synclog.v1.SyncLogService.GetHead:input_type -> synclog.v1.GetHeadRequest
	5,  // 15: synclog.v1.SyncLogService.GetCursor:input_type -> synclog.v1.GetCursorRequest
	7,  // 16: synclog.v1.SyncLogService.CatchUp:input_type -> synclog.v1.CatchUpRequest
	9,  // 17: synclog.v1.SyncLogService.Subscribe:input_type -> synclog.v1.SubscribeRequest
	11, // 18: synclog.v1.SyncLogService.Ack:input_type -> synclog.v1.AckRequest
	2,  // 19: synclog.v1.SyncLogService.Append:output_type -> synclog.v1.AppendResponse
	4,  // 20: synclog.v1.SyncLogService.GetHead:output_type -> synclog.v1.GetHeadResponse
	6,  // 21: synclog.v1.SyncLogService.GetCursor:output_type -> synclog.v1.GetCursorResponse
	8,  // 22: synclog.v1.SyncLogService.CatchUp:output_type -> synclog.v1.CatchUpResponse
	10, // 23: synclog.v1.SyncLogService.Subscribe:output_type -> synclog.v1.SubscribeResponse
	12, // 24: synclog.v1.SyncLogService.Ack:output_type -> synclog.v1.AckResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_synclog_v1_service_proto_init() }
func file_synclog_v1_service_proto_init() {
	if File_synclog_v1_service_proto != nil {
		return
	}
	file_synclog_v1_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synclog_v1_service_proto_rawDesc), len(file_synclog_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synclog_v1_service_proto_goTypes,
		DependencyIndexes: file_synclog_v1_service_proto_depIdxs,
		EnumInfos:         file_synclog_v1_service_proto_enumTypes,
		MessageInfos:      file_synclog_v1_service_proto_msgTypes,
	}.Build()
	File_synclog_v1_service_proto = out.File
	file_synclog_v1_service_proto_goTypes = nil
	file_synclog_v1_service_proto_depIdxs = nil
}
