// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/snapshot.proto

package synclogv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotCompression describes how the opaque snapshot payload is encoded.
type SnapshotCompression int32

const (
	SnapshotCompression_SNAPSHOT_COMPRESSION_NONE SnapshotCompression = 0
	SnapshotCompression_SNAPSHOT_COMPRESSION_GZIP SnapshotCompression = 1
	SnapshotCompression_SNAPSHOT_COMPRESSION_ZSTD SnapshotCompression = 2
)

// Enum value maps for SnapshotCompression.
var (
	SnapshotCompression_name = map[int32]string{
		0: "SNAPSHOT_COMPRESSION_NONE",
		1: "SNAPSHOT_COMPRESSION_GZIP",
		2: "SNAPSHOT_COMPRESSION_ZSTD",
	}
	SnapshotCompression_value = map[string]int32{
		"SNAPSHOT_COMPRESSION_NONE": 0,
		"SNAPSHOT_COMPRESSION_GZIP": 1,
		"SNAPSHOT_COMPRESSION_ZSTD": 2,
	}
)

func (x SnapshotCompression) Enum() *SnapshotCompression {
	p := new(SnapshotCompression)
	*p = x
	return p
}

func (x SnapshotCompression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotCompression) Descriptor() protoreflect.EnumDescriptor {
	return file_synclog_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (SnapshotCompression) Type() protoreflect.EnumType {
	return &file_synclog_v1_snapshot_proto_enumTypes[0]
}

func (x SnapshotCompression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotCompression.Descriptor instead.
func (SnapshotCompression) EnumDescriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

// SnapshotRef is the metadata for one opaque state image. `seq` means the
// snapshot reflects all events in the stream up to and including that seq.
type SnapshotRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq             uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	PayloadType     string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion  uint32                 `protobuf:"varint,4,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	Compression     SnapshotCompression    `protobuf:"varint,5,opt,name=compression,proto3,enum=synclog.v1.SnapshotCompression" json:"compression,omitempty"`
	Checksum        string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,8,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	ProducerId      string                 `protobuf:"bytes,9,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRef) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SnapshotRef) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SnapshotRef) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *SnapshotRef) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

func (x *SnapshotRef) GetCompression() SnapshotCompression {
	if x != nil {
		return x.Compression
	}
	return SnapshotCompression_SNAPSHOT_COMPRESSION_NONE
}

func (x *SnapshotRef) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SnapshotRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotRef) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *SnapshotRef) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

// Snapshot is an opaque state image plus its stream position metadata. Synclog
// stores and serves the bytes but never builds, parses, or applies them.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SnapshotRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetRef() *SnapshotRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Snapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PutSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadType    string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion uint32                 `protobuf:"varint,5,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	Compression    SnapshotCompression    `protobuf:"varint,6,opt,name=compression,proto3,enum=synclog.v1.SnapshotCompression" json:"compression,omitempty"`
	Checksum       string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ProducerId     string                 `protobuf:"bytes,8,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutSnapshotRequest) Reset() {
	*x = PutSnapshotRequest{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSnapshotRequest) ProtoMessage() {}

func (x *PutSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PutSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *PutSnapshotRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *PutSnapshotRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PutSnapshotRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutSnapshotRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *PutSnapshotRequest) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

func (x *PutSnapshotRequest) GetCompression() SnapshotCompression {
	if x != nil {
		return x.Compression
	}
	return SnapshotCompression_SNAPSHOT_COMPRESSION_NONE
}

func (x *PutSnapshotRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PutSnapshotRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

type PutSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRef           `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSnapshotResponse) Reset() {
	*x = PutSnapshotResponse{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSnapshotResponse) ProtoMessage() {}

func (x *PutSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PutSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *PutSnapshotResponse) GetSnapshot() *SnapshotRef {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *PutSnapshotResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetLatestSnapshotRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StreamId    string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	PayloadType string                 `protobuf:"bytes,2,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// 0 means "no upper bound"; otherwise return the newest snapshot whose
	// payload_version is <= max_payload_version.
	MaxPayloadVersion uint32 `protobuf:"varint,3,opt,name=max_payload_version,json=maxPayloadVersion,proto3" json:"max_payload_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLatestSnapshotRequest) Reset() {
	*x = GetLatestSnapshotRequest{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotRequest) ProtoMessage() {}

func (x *GetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestSnapshotRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GetLatestSnapshotRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *GetLatestSnapshotRequest) GetMaxPayloadVersion() uint32 {
	if x != nil {
		return x.MaxPayloadVersion
	}
	return 0
}

type GetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotResponse) Reset() {
	*x = GetLatestSnapshotResponse{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotResponse) ProtoMessage() {}

func (x *GetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	PayloadType    string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion uint32                 `protobuf:"varint,4,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *GetSnapshotRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GetSnapshotRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSnapshotRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *GetSnapshotRequest) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	PayloadType   string                 `protobuf:"bytes,2,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *ListSnapshotsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ListSnapshotsRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *ListSnapshotsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSnapshotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotRef         `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotRef {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListSnapshotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	PayloadType    string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadVersion uint32                 `protobuf:"varint,4,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSnapshotRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeleteSnapshotRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetPayloadVersion() uint32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_synclog_v1_snapshot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_synclog_v1_snapshot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_synclog_v1_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSnapshotResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_synclog_v1_snapshot_proto protoreflect.FileDescriptor

const file_synclog_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x19synclog/v1/snapshot.proto\x12\n" +
	"synclog.v1\x1a\x17validate/validate.proto\"\xf0\x02\n" +
	"\vSnapshotRef\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12*\n" +
	"\fpayload_type\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x04 \x01(\rR\x0epayloadVersion\x12K\n" +
	"\vcompression\x18\x05 \x01(\x0e2\x1f.synclog.v1.SnapshotCompressionB\b\xfaB\x05\x82\x01\x02\x10\x01R\vcompression\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12+\n" +
	"\x12created_at_unix_ms\x18\b \x01(\x03R\x0fcreatedAtUnixMs\x12\x1f\n" +
	"\vproducer_id\x18\t \x01(\tR\n" +
	"producerId\"Y\n" +
	"\bSnapshot\x123\n" +
	"\x03ref\x18\x01 \x01(\v2\x17.synclog.v1.SnapshotRefB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03ref\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xc5\x02\n" +
	"\x12PutSnapshotRequest\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12*\n" +
	"\fpayload_type\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x05 \x01(\rR\x0epayloadVersion\x12K\n" +
	"\vcompression\x18\x06 \x01(\x0e2\x1f.synclog.v1.SnapshotCompressionB\b\xfaB\x05\x82\x01\x02\x10\x01R\vcompression\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1f\n" +
	"\vproducer_id\x18\b \x01(\tR\n" +
	"producerId\"n\n" +
	"\x13PutSnapshotResponse\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.synclog.v1.SnapshotRefR\bsnapshot\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"\x9c\x01\n" +
	"\x18GetLatestSnapshotRequest\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12*\n" +
	"\fpayload_type\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpayloadType\x12.\n" +
	"\x13max_payload_version\x18\x03 \x01(\rR\x11maxPayloadVersion\"M\n" +
	"\x19GetLatestSnapshotResponse\x120\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.synclog.v1.SnapshotR\bsnapshot\"\xa1\x01\n" +
	"\x12GetSnapshotRequest\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12*\n" +
	"\fpayload_type\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x04 \x01(\rR\x0epayloadVersion\"G\n" +
	"\x13GetSnapshotResponse\x120\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.synclog.v1.SnapshotR\bsnapshot\"\x9e\x01\n" +
	"\x14ListSnapshotsRequest\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12!\n" +
	"\fpayload_type\x18\x02 \x01(\tR\vpayloadType\x12\x1e\n" +
	"\x05limit\x18\x03 \x01(\rB\b\xfaB\x05*\x03\x18\xe8\aR\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"v\n" +
	"\x15ListSnapshotsResponse\x125\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x17.synclog.v1.SnapshotRefR\tsnapshots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa4\x01\n" +
	"\x15DeleteSnapshotRequest\x12$\n" +
	"\tstream_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12*\n" +
	"\fpayload_type\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpayloadType\x12'\n" +
	"\x0fpayload_version\x18\x04 \x01(\rR\x0epayloadVersion\"2\n" +
	"\x16DeleteSnapshotResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted*r\n" +
	"\x13SnapshotCompression\x12\x1d\n" +
	"\x19SNAPSHOT_COMPRESSION_NONE\x10\x00\x12\x1d\n" +
	"\x19SNAPSHOT_COMPRESSION_GZIP\x10\x01\x12\x1d\n" +
	"\x19SNAPSHOT_COMPRESSION_ZSTD\x10\x022\xc9\x03\n" +
	"\x16SyncLogSnapshotService\x12N\n" +
	"\vPutSnapshot\x12\x1e.synclog.v1.PutSnapshotRequest\x1a\x1f.synclog.v1.PutSnapshotResponse\x12`\n" +
	"\x11GetLatestSnapshot\x12$.synclog.v1.GetLatestSnapshotRequest\x1a%.synclog.v1.GetLatestSnapshotResponse\x12N\n" +
	"\vGetSnapshot\x12\x1e.synclog.v1.GetSnapshotRequest\x1a\x1f.synclog.v1.GetSnapshotResponse\x12T\n" +
	"\rListSnapshots\x12 .synclog.v1.ListSnapshotsRequest\x1a!.synclog.v1.ListSnapshotsResponse\x12W\n" +
	"\x0eDeleteSnapshot\x12!.synclog.v1.DeleteSnapshotRequest\x1a\".synclog.v1.DeleteSnapshotResponseB<Z:github.com/gopherex/synclog/pkg/proto/synclog/v1;synclogv1b\x06proto3"

var (
	file_synclog_v1_snapshot_proto_rawDescOnce sync.Once
	file_synclog_v1_snapshot_proto_rawDescData []byte
)

func file_synclog_v1_snapshot_proto_rawDescGZIP() []byte {
	file_synclog_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_synclog_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synclog_v1_snapshot_proto_rawDesc), len(file_synclog_v1_snapshot_proto_rawDesc)))
	})
	return file_synclog_v1_snapshot_proto_rawDescData
}

var file_synclog_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synclog_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_synclog_v1_snapshot_proto_goTypes = []any{
	(SnapshotCompression)(0),          // 0: synclog.v1.SnapshotCompression
	(*SnapshotRef)(nil),               // 1: synclog.v1.SnapshotRef
	(*Snapshot)(nil),                  // 2: synclog.v1.Snapshot
	(*PutSnapshotRequest)(nil),        // 3: synclog.v1.PutSnapshotRequest
	(*PutSnapshotResponse)(nil),       // 4: synclog.v1.PutSnapshotResponse
	(*GetLatestSnapshotRequest)(nil),  // 5: synclog.v1.GetLatestSnapshotRequest
	(*GetLatestSnapshotResponse)(nil), // 6: synclog.v1.GetLatestSnapshotResponse
	(*GetSnapshotRequest)(nil),        // 7: synclog.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),       // 8: synclog.v1.GetSnapshotResponse
	(*ListSnapshotsRequest)(nil),      // 9: synclog.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),     // 10: synclog.v1.ListSnapshotsResponse
	(*DeleteSnapshotRequest)(nil),     // 11: synclog.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),    // 12: synclog.v1.DeleteSnapshotResponse
}
var file_synclog_v1_snapshot_proto_depIdxs = []int32{
	0,  // 0: synclog.v1.SnapshotRef.compression:type_name -> synclog.v1.SnapshotCompression
	1,  // 1: synclog.v1.Snapshot.ref:type_name -> synclog.v1.SnapshotRef
	0,  // 2: synclog.v1.PutSnapshotRequest.compression:type_name -> synclog.v1.SnapshotCompression
	1,  // 3: synclog.v1.PutSnapshotResponse.snapshot:type_name -> synclog.v1.SnapshotRef
	2,  // 4: synclog.v1.GetLatestSnapshotResponse.snapshot:type_name -> synclog.v1.Snapshot
	2,  // 5: synclog.v1.GetSnapshotResponse.snapshot:type_name -> synclog.v1.Snapshot
	1,  // 6: synclog.v1.ListSnapshotsResponse.snapshots:type_name -> synclog.v1.SnapshotRef
	3,  // 7: synclog.v1.SyncLogSnapshotService.PutSnapshot:input_type -> synclog.v1.PutSnapshotRequest
	5,  // 8: synclog.v1.SyncLogSnapshotService.GetLatestSnapshot:input_type -> synclog.v1.GetLatestSnapshotRequest
	7,  // 9: synclog.v1.SyncLogSnapshotService.GetSnapshot:input_type -> synclog.v1.GetSnapshotRequest
	9,  // 10: synclog.v1.SyncLogSnapshotService.ListSnapshots:input_type -> synclog.v1.ListSnapshotsRequest
	11, // 11: synclog.v1.SyncLogSnapshotService.DeleteSnapshot:input_type -> synclog.v1.DeleteSnapshotRequest
	4,  // 12: synclog.v1.SyncLogSnapshotService.PutSnapshot:output_type -> synclog.v1.PutSnapshotResponse
	6,  // 13: synclog.v1.SyncLogSnapshotService.GetLatestSnapshot:output_type -> synclog.v1.GetLatestSnapshotResponse
	8,  // 14: synclog.v1.SyncLogSnapshotService.GetSnapshot:output_type -> synclog.v1.GetSnapshotResponse
	10, // 15: synclog.v1.SyncLogSnapshotService.ListSnapshots:output_type -> synclog.v1.ListSnapshotsResponse
	12, // 16: synclog.v1.SyncLogSnapshotService.DeleteSnapshot:output_type -> synclog.v1.DeleteSnapshotResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_synclog_v1_snapshot_proto_init() }
func file_synclog_v1_snapshot_proto_init() {
	if File_synclog_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synclog_v1_snapshot_proto_rawDesc), len(file_synclog_v1_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synclog_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_synclog_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_synclog_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_synclog_v1_snapshot_proto_msgTypes,
	}.Build()
	File_synclog_v1_snapshot_proto = out.File
	file_synclog_v1_snapshot_proto_goTypes = nil
	file_synclog_v1_snapshot_proto_depIdxs = nil
}
