// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: synclog/v1/snapshot.proto

package synclogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncLogSnapshotService_PutSnapshot_FullMethodName       = "/synclog.v1.SyncLogSnapshotService/PutSnapshot"
	SyncLogSnapshotService_GetLatestSnapshot_FullMethodName = "/synclog.v1.SyncLogSnapshotService/GetLatestSnapshot"
	SyncLogSnapshotService_GetSnapshot_FullMethodName       = "/synclog.v1.SyncLogSnapshotService/GetSnapshot"
	SyncLogSnapshotService_ListSnapshots_FullMethodName     = "/synclog.v1.SyncLogSnapshotService/ListSnapshots"
	SyncLogSnapshotService_DeleteSnapshot_FullMethodName    = "/synclog.v1.SyncLogSnapshotService/DeleteSnapshot"
)

// SyncLogSnapshotServiceClient is the client API for SyncLogSnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncLogSnapshotService stores opaque snapshot blobs for stream recovery. It is
// generic: domain services build snapshots externally and publish them here.
type SyncLogSnapshotServiceClient interface {
	// PutSnapshot stores a snapshot for a stream position. Repeating the same
	// stream/type/version/seq/checksum may be treated as idempotent.
	PutSnapshot(ctx context.Context, in *PutSnapshotRequest, opts ...grpc.CallOption) (*PutSnapshotResponse, error)
	// GetLatestSnapshot returns the newest compatible snapshot for a stream/type.
	GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error)
	// GetSnapshot returns an exact snapshot by stream/type/version/seq.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// ListSnapshots returns snapshot metadata without payload bytes.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// DeleteSnapshot removes one snapshot blob and its metadata.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type syncLogSnapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncLogSnapshotServiceClient(cc grpc.ClientConnInterface) SyncLogSnapshotServiceClient {
	return &syncLogSnapshotServiceClient{cc}
}

func (c *syncLogSnapshotServiceClient) PutSnapshot(ctx context.Context, in *PutSnapshotRequest, opts ...grpc.CallOption) (*PutSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncLogSnapshotService_PutSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogSnapshotServiceClient) GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncLogSnapshotService_GetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogSnapshotServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncLogSnapshotService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogSnapshotServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SyncLogSnapshotService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLogSnapshotServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SyncLogSnapshotService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncLogSnapshotServiceServer is the server API for SyncLogSnapshotService service.
// All implementations must embed UnimplementedSyncLogSnapshotServiceServer
// for forward compatibility.
//
// SyncLogSnapshotService stores opaque snapshot blobs for stream recovery. It is
// generic: domain services build snapshots externally and publish them here.
type SyncLogSnapshotServiceServer interface {
	// PutSnapshot stores a snapshot for a stream position. Repeating the same
	// stream/type/version/seq/checksum may be treated as idempotent.
	PutSnapshot(context.Context, *PutSnapshotRequest) (*PutSnapshotResponse, error)
	// GetLatestSnapshot returns the newest compatible snapshot for a stream/type.
	GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error)
	// GetSnapshot returns an exact snapshot by stream/type/version/seq.
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// ListSnapshots returns snapshot metadata without payload bytes.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// DeleteSnapshot removes one snapshot blob and its metadata.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedSyncLogSnapshotServiceServer()
}

// UnimplementedSyncLogSnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncLogSnapshotServiceServer struct{}

func (UnimplementedSyncLogSnapshotServiceServer) PutSnapshot(context.Context, *PutSnapshotRequest) (*PutSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutSnapshot not implemented")
}
func (UnimplementedSyncLogSnapshotServiceServer) GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshot not implemented")
}
func (UnimplementedSyncLogSnapshotServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedSyncLogSnapshotServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedSyncLogSnapshotServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSyncLogSnapshotServiceServer) mustEmbedUnimplementedSyncLogSnapshotServiceServer() {
}
func (UnimplementedSyncLogSnapshotServiceServer) testEmbeddedByValue() {}

// UnsafeSyncLogSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncLogSnapshotServiceServer will
// result in compilation errors.
type UnsafeSyncLogSnapshotServiceServer interface {
	mustEmbedUnimplementedSyncLogSnapshotServiceServer()
}

func RegisterSyncLogSnapshotServiceServer(s grpc.ServiceRegistrar, srv SyncLogSnapshotServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncLogSnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncLogSnapshotService_ServiceDesc, srv)
}

func _SyncLogSnapshotService_PutSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogSnapshotServiceServer).PutSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogSnapshotService_PutSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogSnapshotServiceServer).PutSnapshot(ctx, req.(*PutSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogSnapshotService_GetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogSnapshotServiceServer).GetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogSnapshotService_GetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogSnapshotServiceServer).GetLatestSnapshot(ctx, req.(*GetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogSnapshotService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogSnapshotServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogSnapshotService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogSnapshotServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogSnapshotService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogSnapshotServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogSnapshotService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogSnapshotServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLogSnapshotService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLogSnapshotServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLogSnapshotService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLogSnapshotServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncLogSnapshotService_ServiceDesc is the grpc.ServiceDesc for SyncLogSnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncLogSnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synclog.v1.SyncLogSnapshotService",
	HandlerType: (*SyncLogSnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutSnapshot",
			Handler:    _SyncLogSnapshotService_PutSnapshot_Handler,
		},
		{
			MethodName: "GetLatestSnapshot",
			Handler:    _SyncLogSnapshotService_GetLatestSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _SyncLogSnapshotService_GetSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _SyncLogSnapshotService_ListSnapshots_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SyncLogSnapshotService_DeleteSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synclog/v1/snapshot.proto",
}
