// @generated by protoc-gen-es v2.11.0 with parameter "import_extension=js,json_types=true,target=ts,valid_types=legacy_required+protovalidate_required"
// @generated from file synclog/v1/event.proto (package synclog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_validate_validate } from "../../validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file synclog/v1/event.proto.
 */
export const file_synclog_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChZzeW5jbG9nL3YxL2V2ZW50LnByb3RvEgpzeW5jbG9nLnYxIh0KBlN0cmVhbRITCgJpZBgBIAEoCUIH+kIEcgIQASIxCgZDdXJzb3ISGgoJc3RyZWFtX2lkGAEgASgJQgf6QgRyAhABEgsKA3NlcRgCIAEoBCKOAQoQU3Vic2NyaWJlckN1cnNvchIeCg1zdWJzY3JpYmVyX2lkGAEgASgJQgf6QgRyAhABEiwKBmN1cnNvchgCIAEoCzISLnN5bmNsb2cudjEuQ3Vyc29yQgj6QgWKAQIQARIQCghtZXRhZGF0YRgDIAEoCRIaChJ1cGRhdGVkX2F0X3VuaXhfbXMYBCABKAMirgEKBUV2ZW50EhoKCXN0cmVhbV9pZBgBIAEoCUIH+kIEcgIQARIUCgNzZXEYAiABKARCB/pCBDICIAASDwoHcGF5bG9hZBgDIAEoDBIUCgxwYXlsb2FkX3R5cGUYBCABKAkSFwoPcGF5bG9hZF92ZXJzaW9uGAUgASgNEhcKD2lkZW1wb3RlbmN5X2tleRgGIAEoCRIaChJjcmVhdGVkX2F0X3VuaXhfbXMYByABKAMiXgoKRXZlbnRCYXRjaBIhCgZldmVudHMYASADKAsyES5zeW5jbG9nLnYxLkV2ZW50EhEKCXNlcV9zdGFydBgCIAEoBBILCgNzZXEYAyABKAQSDQoFZmluYWwYBCABKAhCPFo6Z2l0aHViLmNvbS9nb3BoZXJleC9zeW5jbG9nL3BrZy9wcm90by9zeW5jbG9nL3YxO3N5bmNsb2d2MWIGcHJvdG8z", [file_validate_validate]);

/**
 * Stream is an ordered, append-only sequence of events. A subscriber that maps
 * many logical sources onto streams decides the granularity (e.g. one shared
 * stream for many small sources, a dedicated stream for a high-volume one).
 *
 * @generated from message synclog.v1.Stream
 */
export type Stream = Message<"synclog.v1.Stream"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Stream is an ordered, append-only sequence of events. A subscriber that maps
 * many logical sources onto streams decides the granularity (e.g. one shared
 * stream for many small sources, a dedicated stream for a high-volume one).
 *
 * @generated from message synclog.v1.Stream
 */
export type StreamJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;
};

export type StreamValid = Stream;

/**
 * Describes the message synclog.v1.Stream.
 * Use `create(StreamSchema)` to create a new message.
 */
export const StreamSchema: GenMessage<Stream, {jsonType: StreamJson, validType: StreamValid}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 0);

/**
 * Cursor is a monotonic position within a stream. Equivalent to Telegram's
 * per-box `pts`; in the server-managed mode the service stores one cursor per
 * subscriber and stream.
 *
 * @generated from message synclog.v1.Cursor
 */
export type Cursor = Message<"synclog.v1.Cursor"> & {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq: bigint;
};

/**
 * Cursor is a monotonic position within a stream. Equivalent to Telegram's
 * per-box `pts`; in the server-managed mode the service stores one cursor per
 * subscriber and stream.
 *
 * @generated from message synclog.v1.Cursor
 */
export type CursorJson = {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId?: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq?: string;
};

export type CursorValid = Cursor;

/**
 * Describes the message synclog.v1.Cursor.
 * Use `create(CursorSchema)` to create a new message.
 */
export const CursorSchema: GenMessage<Cursor, {jsonType: CursorJson, validType: CursorValid}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 1);

/**
 * SubscriberCursor is the stored server-side cursor for one subscriber/stream
 * pair. It is used by admin and diagnostics surfaces.
 *
 * @generated from message synclog.v1.SubscriberCursor
 */
export type SubscriberCursor = Message<"synclog.v1.SubscriberCursor"> & {
  /**
   * @generated from field: string subscriber_id = 1;
   */
  subscriberId: string;

  /**
   * @generated from field: synclog.v1.Cursor cursor = 2;
   */
  cursor?: Cursor;

  /**
   * @generated from field: string metadata = 3;
   */
  metadata: string;

  /**
   * @generated from field: int64 updated_at_unix_ms = 4;
   */
  updatedAtUnixMs: bigint;
};

/**
 * SubscriberCursor is the stored server-side cursor for one subscriber/stream
 * pair. It is used by admin and diagnostics surfaces.
 *
 * @generated from message synclog.v1.SubscriberCursor
 */
export type SubscriberCursorJson = {
  /**
   * @generated from field: string subscriber_id = 1;
   */
  subscriberId?: string;

  /**
   * @generated from field: synclog.v1.Cursor cursor = 2;
   */
  cursor?: CursorJson;

  /**
   * @generated from field: string metadata = 3;
   */
  metadata?: string;

  /**
   * @generated from field: int64 updated_at_unix_ms = 4;
   */
  updatedAtUnixMs?: string;
};

export type SubscriberCursorValid = SubscriberCursor;

/**
 * Describes the message synclog.v1.SubscriberCursor.
 * Use `create(SubscriberCursorSchema)` to create a new message.
 */
export const SubscriberCursorSchema: GenMessage<SubscriberCursor, {jsonType: SubscriberCursorJson, validType: SubscriberCursorValid}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 2);

/**
 * Event is one entry in a stream. `payload` is opaque to synclog: the producer
 * serializes a domain object into it; synclog never parses it. The type/version
 * fields are routing hints for SDK codecs and consumers, not schema knowledge.
 *
 * @generated from message synclog.v1.Event
 */
export type Event = Message<"synclog.v1.Event"> & {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq: bigint;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;

  /**
   * @generated from field: string payload_type = 4;
   */
  payloadType: string;

  /**
   * @generated from field: uint32 payload_version = 5;
   */
  payloadVersion: number;

  /**
   * @generated from field: string idempotency_key = 6;
   */
  idempotencyKey: string;

  /**
   * @generated from field: int64 created_at_unix_ms = 7;
   */
  createdAtUnixMs: bigint;
};

/**
 * Event is one entry in a stream. `payload` is opaque to synclog: the producer
 * serializes a domain object into it; synclog never parses it. The type/version
 * fields are routing hints for SDK codecs and consumers, not schema knowledge.
 *
 * @generated from message synclog.v1.Event
 */
export type EventJson = {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId?: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq?: string;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload?: string;

  /**
   * @generated from field: string payload_type = 4;
   */
  payloadType?: string;

  /**
   * @generated from field: uint32 payload_version = 5;
   */
  payloadVersion?: number;

  /**
   * @generated from field: string idempotency_key = 6;
   */
  idempotencyKey?: string;

  /**
   * @generated from field: int64 created_at_unix_ms = 7;
   */
  createdAtUnixMs?: string;
};

export type EventValid = Event;

/**
 * Describes the message synclog.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event, {jsonType: EventJson, validType: EventValid}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 3);

/**
 * EventBatch is a contiguous, ordered run of events. `seq_start`..`seq` lets a
 * consumer detect gaps and de-duplicate (Telegram `updates`/`updatesCombined`).
 *
 * @generated from message synclog.v1.EventBatch
 */
export type EventBatch = Message<"synclog.v1.EventBatch"> & {
  /**
   * @generated from field: repeated synclog.v1.Event events = 1;
   */
  events: Event[];

  /**
   * @generated from field: uint64 seq_start = 2;
   */
  seqStart: bigint;

  /**
   * @generated from field: uint64 seq = 3;
   */
  seq: bigint;

  /**
   * True when the batch reaches the current head of the stream; false means the
   * consumer should CatchUp again (Telegram differenceSlice semantics).
   *
   * @generated from field: bool final = 4;
   */
  final: boolean;
};

/**
 * EventBatch is a contiguous, ordered run of events. `seq_start`..`seq` lets a
 * consumer detect gaps and de-duplicate (Telegram `updates`/`updatesCombined`).
 *
 * @generated from message synclog.v1.EventBatch
 */
export type EventBatchJson = {
  /**
   * @generated from field: repeated synclog.v1.Event events = 1;
   */
  events?: EventJson[];

  /**
   * @generated from field: uint64 seq_start = 2;
   */
  seqStart?: string;

  /**
   * @generated from field: uint64 seq = 3;
   */
  seq?: string;

  /**
   * True when the batch reaches the current head of the stream; false means the
   * consumer should CatchUp again (Telegram differenceSlice semantics).
   *
   * @generated from field: bool final = 4;
   */
  final?: boolean;
};

export type EventBatchValid = EventBatch;

/**
 * Describes the message synclog.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch, {jsonType: EventBatchJson, validType: EventBatchValid}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 4);

