// @generated by protoc-gen-es v2.11.0 with parameter "import_extension=js,json_types=true,target=ts"
// @generated from file synclog/v1/event.proto (package synclog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file synclog/v1/event.proto.
 */
export const file_synclog_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChZzeW5jbG9nL3YxL2V2ZW50LnByb3RvEgpzeW5jbG9nLnYxIhQKBlN0cmVhbRIKCgJpZBgBIAEoCSIoCgZDdXJzb3ISEQoJc3RyZWFtX2lkGAEgASgJEgsKA3NlcRgCIAEoBCJ7ChBTdWJzY3JpYmVyQ3Vyc29yEhUKDXN1YnNjcmliZXJfaWQYASABKAkSIgoGY3Vyc29yGAIgASgLMhIuc3luY2xvZy52MS5DdXJzb3ISEAoIbWV0YWRhdGEYAyABKAkSGgoSdXBkYXRlZF9hdF91bml4X21zGAQgASgDIpwBCgVFdmVudBIRCglzdHJlYW1faWQYASABKAkSCwoDc2VxGAIgASgEEg8KB3BheWxvYWQYAyABKAwSFAoMcGF5bG9hZF90eXBlGAQgASgJEhcKD3BheWxvYWRfdmVyc2lvbhgFIAEoDRIXCg9pZGVtcG90ZW5jeV9rZXkYBiABKAkSGgoSY3JlYXRlZF9hdF91bml4X21zGAcgASgDIl4KCkV2ZW50QmF0Y2gSIQoGZXZlbnRzGAEgAygLMhEuc3luY2xvZy52MS5FdmVudBIRCglzZXFfc3RhcnQYAiABKAQSCwoDc2VxGAMgASgEEg0KBWZpbmFsGAQgASgIQjxaOmdpdGh1Yi5jb20vZ29waGVyZXgvc3luY2xvZy9wa2cvcHJvdG8vc3luY2xvZy92MTtzeW5jbG9ndjFiBnByb3RvMw");

/**
 * Stream is an ordered, append-only sequence of events. A subscriber that maps
 * many logical sources onto streams decides the granularity (e.g. one shared
 * stream for many small sources, a dedicated stream for a high-volume one).
 *
 * @generated from message synclog.v1.Stream
 */
export type Stream = Message<"synclog.v1.Stream"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Stream is an ordered, append-only sequence of events. A subscriber that maps
 * many logical sources onto streams decides the granularity (e.g. one shared
 * stream for many small sources, a dedicated stream for a high-volume one).
 *
 * @generated from message synclog.v1.Stream
 */
export type StreamJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message synclog.v1.Stream.
 * Use `create(StreamSchema)` to create a new message.
 */
export const StreamSchema: GenMessage<Stream, {jsonType: StreamJson}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 0);

/**
 * Cursor is a monotonic position within a stream. Equivalent to Telegram's
 * per-box `pts`; in the server-managed mode the service stores one cursor per
 * subscriber and stream.
 *
 * @generated from message synclog.v1.Cursor
 */
export type Cursor = Message<"synclog.v1.Cursor"> & {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq: bigint;
};

/**
 * Cursor is a monotonic position within a stream. Equivalent to Telegram's
 * per-box `pts`; in the server-managed mode the service stores one cursor per
 * subscriber and stream.
 *
 * @generated from message synclog.v1.Cursor
 */
export type CursorJson = {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId?: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq?: string;
};

/**
 * Describes the message synclog.v1.Cursor.
 * Use `create(CursorSchema)` to create a new message.
 */
export const CursorSchema: GenMessage<Cursor, {jsonType: CursorJson}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 1);

/**
 * SubscriberCursor is the stored server-side cursor for one subscriber/stream
 * pair. It is used by admin and diagnostics surfaces.
 *
 * @generated from message synclog.v1.SubscriberCursor
 */
export type SubscriberCursor = Message<"synclog.v1.SubscriberCursor"> & {
  /**
   * @generated from field: string subscriber_id = 1;
   */
  subscriberId: string;

  /**
   * @generated from field: synclog.v1.Cursor cursor = 2;
   */
  cursor?: Cursor;

  /**
   * @generated from field: string metadata = 3;
   */
  metadata: string;

  /**
   * @generated from field: int64 updated_at_unix_ms = 4;
   */
  updatedAtUnixMs: bigint;
};

/**
 * SubscriberCursor is the stored server-side cursor for one subscriber/stream
 * pair. It is used by admin and diagnostics surfaces.
 *
 * @generated from message synclog.v1.SubscriberCursor
 */
export type SubscriberCursorJson = {
  /**
   * @generated from field: string subscriber_id = 1;
   */
  subscriberId?: string;

  /**
   * @generated from field: synclog.v1.Cursor cursor = 2;
   */
  cursor?: CursorJson;

  /**
   * @generated from field: string metadata = 3;
   */
  metadata?: string;

  /**
   * @generated from field: int64 updated_at_unix_ms = 4;
   */
  updatedAtUnixMs?: string;
};

/**
 * Describes the message synclog.v1.SubscriberCursor.
 * Use `create(SubscriberCursorSchema)` to create a new message.
 */
export const SubscriberCursorSchema: GenMessage<SubscriberCursor, {jsonType: SubscriberCursorJson}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 2);

/**
 * Event is one entry in a stream. `payload` is opaque to synclog: the producer
 * serializes a domain object into it; synclog never parses it. The type/version
 * fields are routing hints for SDK codecs and consumers, not schema knowledge.
 *
 * @generated from message synclog.v1.Event
 */
export type Event = Message<"synclog.v1.Event"> & {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq: bigint;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;

  /**
   * @generated from field: string payload_type = 4;
   */
  payloadType: string;

  /**
   * @generated from field: uint32 payload_version = 5;
   */
  payloadVersion: number;

  /**
   * @generated from field: string idempotency_key = 6;
   */
  idempotencyKey: string;

  /**
   * @generated from field: int64 created_at_unix_ms = 7;
   */
  createdAtUnixMs: bigint;
};

/**
 * Event is one entry in a stream. `payload` is opaque to synclog: the producer
 * serializes a domain object into it; synclog never parses it. The type/version
 * fields are routing hints for SDK codecs and consumers, not schema knowledge.
 *
 * @generated from message synclog.v1.Event
 */
export type EventJson = {
  /**
   * @generated from field: string stream_id = 1;
   */
  streamId?: string;

  /**
   * @generated from field: uint64 seq = 2;
   */
  seq?: string;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload?: string;

  /**
   * @generated from field: string payload_type = 4;
   */
  payloadType?: string;

  /**
   * @generated from field: uint32 payload_version = 5;
   */
  payloadVersion?: number;

  /**
   * @generated from field: string idempotency_key = 6;
   */
  idempotencyKey?: string;

  /**
   * @generated from field: int64 created_at_unix_ms = 7;
   */
  createdAtUnixMs?: string;
};

/**
 * Describes the message synclog.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event, {jsonType: EventJson}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 3);

/**
 * EventBatch is a contiguous, ordered run of events. `seq_start`..`seq` lets a
 * consumer detect gaps and de-duplicate (Telegram `updates`/`updatesCombined`).
 *
 * @generated from message synclog.v1.EventBatch
 */
export type EventBatch = Message<"synclog.v1.EventBatch"> & {
  /**
   * @generated from field: repeated synclog.v1.Event events = 1;
   */
  events: Event[];

  /**
   * @generated from field: uint64 seq_start = 2;
   */
  seqStart: bigint;

  /**
   * @generated from field: uint64 seq = 3;
   */
  seq: bigint;

  /**
   * True when the batch reaches the current head of the stream; false means the
   * consumer should CatchUp again (Telegram differenceSlice semantics).
   *
   * @generated from field: bool final = 4;
   */
  final: boolean;
};

/**
 * EventBatch is a contiguous, ordered run of events. `seq_start`..`seq` lets a
 * consumer detect gaps and de-duplicate (Telegram `updates`/`updatesCombined`).
 *
 * @generated from message synclog.v1.EventBatch
 */
export type EventBatchJson = {
  /**
   * @generated from field: repeated synclog.v1.Event events = 1;
   */
  events?: EventJson[];

  /**
   * @generated from field: uint64 seq_start = 2;
   */
  seqStart?: string;

  /**
   * @generated from field: uint64 seq = 3;
   */
  seq?: string;

  /**
   * True when the batch reaches the current head of the stream; false means the
   * consumer should CatchUp again (Telegram differenceSlice semantics).
   *
   * @generated from field: bool final = 4;
   */
  final?: boolean;
};

/**
 * Describes the message synclog.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch, {jsonType: EventBatchJson}> = /*@__PURE__*/
  messageDesc(file_synclog_v1_event, 4);

